import { notFound } from "next/navigation";
import { eq, and } from "drizzle-orm";

import { db } from "@/db";
import { classes, classWeekdays } from "@/db/schema";
import { RecurringSessionsManager } from "@/components/classes/RecurringSessionsManager";
import { Breadcrumb } from "@/components/ui/breadcrumb";

interface PageProps {
  params: {
    academyId: string;
    classId: string;
  };
}

export default async function RecurringSessionsPage({ params }: PageProps) {
  const { academyId, classId } = params;

  const [classRow] = await db
    .select({
      id: classes.id,
      name: classes.name,
      academyId: classes.academyId,
      startTime: classes.startTime,
      endTime: classes.endTime,
      autoGenerateSessions: classes.autoGenerateSessions,
      autoGenerateFrequency: classes.autoGenerateFrequency,
      lastAutoGeneratedAt: classes.lastAutoGeneratedAt,
      autoGenerateDaysAhead: classes.autoGenerateDaysAhead,
    })
    .from(classes)
    .where(eq(classes.id, classId))
    .limit(1);

  if (!classRow || classRow.academyId !== academyId) {
    notFound();
  }

  const weekdayRows = await db
    .select({
      weekday: classWeekdays.weekday,
    })
    .from(classWeekdays)
    .where(eq(classWeekdays.classId, classId));

  const weekdays = weekdayRows.map((row) => row.weekday).sort((a, b) => a - b);

  return (
    <div className="space-y-6 p-4 sm:p-6 lg:p-8">
      <Breadcrumb
        items={[
          { label: "Dashboard", href: `/app/${academyId}/dashboard` },
          { label: "Clases", href: `/app/${academyId}/classes` },
          { label: classRow.name || "Clase", href: `/app/${academyId}/classes/${classId}` },
          { label: "Sesiones Recurrentes" },
        ]}
      />
      <div>
        <h1 className="text-2xl font-bold">Sesiones Recurrentes</h1>
        <p className="text-muted-foreground mt-1">
          Configuración de generación automática para {classRow.name}
        </p>
      </div>

      <RecurringSessionsManager
        classId={classId}
        className={classRow.name ?? "Clase"}
        weekdays={weekdays}
        startTime={classRow.startTime}
        endTime={classRow.endTime}
        autoGenerateSessions={classRow.autoGenerateSessions ?? false}
        autoGenerateFrequency={classRow.autoGenerateFrequency}
        lastAutoGeneratedAt={classRow.lastAutoGeneratedAt?.toISOString() || null}
        autoGenerateDaysAhead={classRow.autoGenerateDaysAhead ?? 30}
        onSettingsUpdated={() => {
          // Callback para actualizar después de guardar
        }}
      />
    </div>
  );
}

