export type CityOption = {
  value: string;
  label: string;
};

export type RegionCities = {
  [regionValue: string]: CityOption[];
};

// Ciudades por región para cada país
export const CITIES_BY_REGION: {
  [countryValue: string]: RegionCities;
} = {
  es: {
    andalucia: [
      { value: "almeria", label: "Almería" },
      { value: "cadiz", label: "Cádiz" },
      { value: "cordoba", label: "Córdoba" },
      { value: "granada", label: "Granada" },
      { value: "huelva", label: "Huelva" },
      { value: "jaen", label: "Jaén" },
      { value: "malaga", label: "Málaga" },
      { value: "sevilla", label: "Sevilla" },
      { value: "jerez", label: "Jerez de la Frontera" },
      { value: "marbella", label: "Marbella" },
      { value: "algeciras", label: "Algeciras" },
      { value: "dos-hermanas", label: "Dos Hermanas" },
      { value: "el-ejido", label: "El Ejido" },
      { value: "rota", label: "Rota" },
      { value: "sanlucar", label: "Sanlúcar de Barrameda" },
      { value: "ubeda", label: "Úbeda" },
      { value: "linares", label: "Linares" },
      { value: "motril", label: "Motril" },
      { value: "fuengirola", label: "Fuengirola" },
      { value: "torremolinos", label: "Torremolinos" },
      { value: "benalmadena", label: "Benalmádena" },
      { value: "estepona", label: "Estepona" },
      { value: "velez-malaga", label: "Vélez-Málaga" },
      { value: "alcala-guadaira", label: "Alcalá de Guadaíra" },
      { value: "lepe", label: "Lepe" },
      { value: "ayamonte", label: "Ayamonte" },
    ],
    aragon: [
      { value: "huesca", label: "Huesca" },
      { value: "teruel", label: "Teruel" },
      { value: "zaragoza", label: "Zaragoza" },
      { value: "calatayud", label: "Calatayud" },
      { value: "ejeca", label: "Éjeca" },
      { value: "barbastro", label: "Barbastro" },
      { value: "monzon", label: "Monzón" },
      { value: "fraga", label: "Fraga" },
      { value: "alcaniz", label: "Alcañiz" },
      { value: "utiel", label: "Utiel" },
    ],
    asturias: [
      { value: "oviedo", label: "Oviedo" },
      { value: "gijon", label: "Gijón" },
      { value: "aviles", label: "Avilés" },
    ],
    baleares: [
      { value: "palma", label: "Palma de Mallorca" },
      { value: "mahon", label: "Mahón" },
      { value: "ibiza", label: "Ibiza" },
    ],
    canarias: [
      { value: "las-palmas", label: "Las Palmas de Gran Canaria" },
      { value: "santa-cruz-tenerife", label: "Santa Cruz de Tenerife" },
      { value: "san-cristobal", label: "San Cristóbal de La Laguna" },
    ],
    cantabria: [
      { value: "santander", label: "Santander" },
      { value: "torrelavega", label: "Torrelavega" },
    ],
    "castilla-la-mancha": [
      { value: "albacete", label: "Albacete" },
      { value: "ciudad-real", label: "Ciudad Real" },
      { value: "cuenca", label: "Cuenca" },
      { value: "guadalajara", label: "Guadalajara" },
      { value: "toledo", label: "Toledo" },
      { value: "talavera", label: "Talavera de la Reina" },
      { value: "puertollano", label: "Puertollano" },
      { value: "tomelloso", label: "Tomelloso" },
      { value: "hellin", label: "Hellín" },
      { value: "villarrobledo", label: "Villarrobledo" },
      { value: "almodovar", label: "Almodóvar del Campo" },
      { value: "valdepenas", label: "Valdepeñas" },
      { value: "manzanares", label: "Manzanares" },
      { value: "alcazar", label: "Alcázar de San Juan" },
      { value: "azuqueca", label: "Azuqueca de Henares" },
    ],
    "castilla-y-leon": [
      { value: "avila", label: "Ávila" },
      { value: "burgos", label: "Burgos" },
      { value: "leon", label: "León" },
      { value: "palencia", label: "Palencia" },
      { value: "salamanca", label: "Salamanca" },
      { value: "segovia", label: "Segovia" },
      { value: "soria", label: "Soria" },
      { value: "valladolid", label: "Valladolid" },
      { value: "zamora", label: "Zamora" },
      { value: "ponferrada", label: "Ponferrada" },
      { value: "santander", label: "Santander" },
      { value: "aranda", label: "Aranda de Duero" },
      { value: "miranda", label: "Miranda de Ebro" },
      { value: "medina", label: "Medina del Campo" },
      { value: "peñafiel", label: "Peñafiel" },
      { value: "astorga", label: "Astorga" },
      { value: "benavente", label: "Benavente" },
      { value: "ciudad-rodrigo", label: "Ciudad Rodrigo" },
      { value: "bejar", label: "Béjar" },
      { value: "arevalo", label: "Arévalo" },
    ],
    catalunya: [
      { value: "barcelona", label: "Barcelona" },
      { value: "girona", label: "Girona" },
      { value: "lleida", label: "Lleida" },
      { value: "tarragona", label: "Tarragona" },
      { value: "badalona", label: "Badalona" },
      { value: "sabadell", label: "Sabadell" },
      { value: "terrassa", label: "Terrassa" },
      { value: "santa-coloma", label: "Santa Coloma de Gramenet" },
      { value: "mataro", label: "Mataró" },
      { value: "sant-cugat", label: "Sant Cugat del Vallès" },
      { value: "rubi", label: "Rubí" },
      { value: "vilanova", label: "Vilanova i la Geltrú" },
      { value: "manresa", label: "Manresa" },
      { value: "reus", label: "Reus" },
      { value: "figueres", label: "Figueres" },
      { value: "blanes", label: "Blanes" },
      { value: "lloret", label: "Lloret de Mar" },
      { value: "sitges", label: "Sitges" },
      { value: "igualada", label: "Igualada" },
      { value: "vic", label: "Vic" },
    ],
    ceuta: [{ value: "ceuta", label: "Ceuta" }],
    extremadura: [
      { value: "badajoz", label: "Badajoz" },
      { value: "caceres", label: "Cáceres" },
    ],
    galicia: [
      { value: "a-coruna", label: "A Coruña" },
      { value: "lugo", label: "Lugo" },
      { value: "ourense", label: "Ourense" },
      { value: "pontevedra", label: "Pontevedra" },
      { value: "vigo", label: "Vigo" },
      { value: "santiago", label: "Santiago de Compostela" },
      { value: "ferrol", label: "Ferrol" },
      { value: "narón", label: "Narón" },
      { value: "oleiros", label: "Oleiros" },
      { value: "arteixo", label: "Arteixo" },
      { value: "ribeira", label: "Ribeira" },
      { value: "monforte", label: "Monforte de Lemos" },
      { value: "vilalba", label: "Vilalba" },
      { value: "sarria", label: "Sarria" },
      { value: "verin", label: "Verín" },
      { value: "carballino", label: "O Carballiño" },
      { value: "xinzo", label: "Xinzo de Limia" },
      { value: "ponteareas", label: "Ponteareas" },
      { value: "redondela", label: "Redondela" },
      { value: "marin", label: "Marín" },
    ],
    "la-rioja": [{ value: "logrono", label: "Logroño" }],
    madrid: [
      { value: "madrid", label: "Madrid" },
      { value: "mostoles", label: "Móstoles" },
      { value: "alcala-henares", label: "Alcalá de Henares" },
      { value: "getafe", label: "Getafe" },
      { value: "leganes", label: "Leganés" },
      { value: "alcobendas", label: "Alcobendas" },
      { value: "fuenlabrada", label: "Fuenlabrada" },
      { value: "coslada", label: "Coslada" },
      { value: "parla", label: "Parla" },
      { value: "las-rozas", label: "Las Rozas de Madrid" },
      { value: "san-sebastian-los-reyes", label: "San Sebastián de los Reyes" },
      { value: "pozuelo-de-alarcon", label: "Pozuelo de Alarcón" },
      { value: "rivas-vaciamadrid", label: "Rivas-Vaciamadrid" },
      { value: "vallecas", label: "Vallecas" },
      { value: "villaverde", label: "Villaverde" },
      { value: "carabanchel", label: "Carabanchel" },
      { value: "tetuan", label: "Tetuán" },
      { value: "chamartin", label: "Chamartín" },
      { value: "salamanca", label: "Salamanca" },
      { value: "chamberi", label: "Chamberí" },
    ],
    melilla: [{ value: "melilla", label: "Melilla" }],
    murcia: [
      { value: "murcia", label: "Murcia" },
      { value: "cartagena", label: "Cartagena" },
      { value: "lorca", label: "Lorca" },
      { value: "mazarron", label: "Mazarrón" },
      { value: "yecla", label: "Yecla" },
      { value: "caravaca", label: "Caravaca de la Cruz" },
      { value: "cehegin", label: "Cehegín" },
      { value: "totana", label: "Totana" },
      { value: "aguilas", label: "Águilas" },
      { value: "san-javier", label: "San Javier" },
      { value: "molina", label: "Molina de Segura" },
      { value: "alcantarilla", label: "Alcantarilla" },
      { value: "ceuti", label: "Ceutí" },
      { value: "las-torres", label: "Las Torres de Cotillas" },
      { value: "archena", label: "Archena" },
    ],
    navarra: [
      { value: "pamplona", label: "Pamplona" },
      { value: "tudela", label: "Tudela" },
    ],
    "pais-vasco": [
      { value: "bilbao", label: "Bilbao" },
      { value: "donostia", label: "Donostia-San Sebastián" },
      { value: "vitoria-gasteiz", label: "Vitoria-Gasteiz" },
    ],
    valencia: [
      { value: "valencia", label: "Valencia" },
      { value: "alicante", label: "Alicante" },
      { value: "castellon", label: "Castellón de la Plana" },
      { value: "elche", label: "Elche" },
      { value: "torrent", label: "Torrent" },
      { value: "gandia", label: "Gandía" },
      { value: "sagunto", label: "Sagunto" },
      { value: "paterna", label: "Paterna" },
      { value: "benidorm", label: "Benidorm" },
      { value: "orihuela", label: "Orihuela" },
      { value: "torrevieja", label: "Torrevieja" },
      { value: "denia", label: "Dénia" },
      { value: "villajoyosa", label: "Villajoyosa" },
      { value: "xativa", label: "Xàtiva" },
      { value: "alcoy", label: "Alcoy" },
      { value: "elda", label: "Elda" },
      { value: "villena", label: "Villena" },
      { value: "benicassim", label: "Benicàssim" },
      { value: "vila-real", label: "Vila-real" },
      { value: "burriana", label: "Burriana" },
    ],
  },
  mx: {
    ags: [
      { value: "aguascalientes", label: "Aguascalientes" },
      { value: "jesus-maria", label: "Jesús María" },
    ],
    bc: [
      { value: "tijuana", label: "Tijuana" },
      { value: "mexicali", label: "Mexicali" },
      { value: "ensenada", label: "Ensenada" },
      { value: "rosarito", label: "Playas de Rosarito" },
    ],
    bcs: [
      { value: "la-paz", label: "La Paz" },
      { value: "cabo-san-lucas", label: "Cabo San Lucas" },
      { value: "san-jose-del-cabo", label: "San José del Cabo" },
    ],
    cam: [
      { value: "campeche", label: "Campeche" },
      { value: "ciudad-del-carmen", label: "Ciudad del Carmen" },
    ],
    chp: [
      { value: "tuxtla-gutierrez", label: "Tuxtla Gutiérrez" },
      { value: "tapachula", label: "Tapachula" },
      { value: "san-cristobal", label: "San Cristóbal de las Casas" },
    ],
    chh: [
      { value: "chihuahua", label: "Chihuahua" },
      { value: "ciudad-juarez", label: "Ciudad Juárez" },
      { value: "parral", label: "Hidalgo del Parral" },
    ],
    cmx: [
      { value: "ciudad-mexico", label: "Ciudad de México" },
      { value: "iztapalapa", label: "Iztapalapa" },
      { value: "gustavo-madero", label: "Gustavo A. Madero" },
      { value: "alvaro-obregon", label: "Álvaro Obregón" },
      { value: "azcapotzalco", label: "Azcapotzalco" },
      { value: "benito-juarez", label: "Benito Juárez" },
      { value: "coyoacan", label: "Coyoacán" },
      { value: "cuajimalpa", label: "Cuajimalpa de Morelos" },
      { value: "cuauhtemoc", label: "Cuauhtémoc" },
      { value: "iztacalco", label: "Iztacalco" },
      { value: "magdalena-contreras", label: "La Magdalena Contreras" },
      { value: "miguel-hidalgo", label: "Miguel Hidalgo" },
      { value: "milpa-alta", label: "Milpa Alta" },
      { value: "tlahuac", label: "Tláhuac" },
      { value: "tlalpan", label: "Tlalpan" },
      { value: "venustiano-carranza", label: "Venustiano Carranza" },
      { value: "xochimilco", label: "Xochimilco" },
    ],
    coah: [
      { value: "saltillo", label: "Saltillo" },
      { value: "torreon", label: "Torreón" },
      { value: "monclova", label: "Monclova" },
    ],
    col: [{ value: "colima", label: "Colima" }, { value: "manzanillo", label: "Manzanillo" }],
    dgo: [
      { value: "durango", label: "Durango" },
      { value: "gomez-palacio", label: "Gómez Palacio" },
    ],
    gto: [
      { value: "guanajuato", label: "Guanajuato" },
      { value: "leon", label: "León" },
      { value: "celaya", label: "Celaya" },
      { value: "salamanca", label: "Salamanca" },
      { value: "irosto", label: "Irapuato" },
      { value: "silao", label: "Silao" },
      { value: "san-miguel", label: "San Miguel de Allende" },
      { value: "dolores-hidalgo", label: "Dolores Hidalgo" },
      { value: "san-francisco", label: "San Francisco del Rincón" },
      { value: "purisima", label: "Purísima del Rincón" },
      { value: "valle-santiago", label: "Valle de Santiago" },
      { value: "moroleon", label: "Moroleón" },
      { value: "yuriria", label: "Yuriria" },
      { value: "penjamo", label: "Pénjamo" },
      { value: "abasolo", label: "Abasolo" },
    ],
    gro: [
      { value: "chilpancingo", label: "Chilpancingo de los Bravo" },
      { value: "acapulco", label: "Acapulco de Juárez" },
      { value: "taxco", label: "Taxco de Alarcón" },
    ],
    hgo: [
      { value: "pachuca", label: "Pachuca de Soto" },
      { value: "tulancingo", label: "Tulancingo" },
    ],
    jal: [
      { value: "guadalajara", label: "Guadalajara" },
      { value: "zapopan", label: "Zapopan" },
      { value: "tlaquepaque", label: "Tlaquepaque" },
      { value: "tonala", label: "Tonalá" },
      { value: "tlajomulco", label: "Tlajomulco de Zúñiga" },
      { value: "el-salto", label: "El Salto" },
      { value: "puerto-vallarta", label: "Puerto Vallarta" },
      { value: "tlaquepaque", label: "San Pedro Tlaquepaque" },
      { value: "ocotlan", label: "Ocotlán" },
      { value: "ciudad-guzman", label: "Ciudad Guzmán" },
      { value: "lago-de-moreno", label: "Lagos de Moreno" },
      { value: "tepatitlan", label: "Tepatitlán de Morelos" },
      { value: "tala", label: "Tala" },
      { value: "ameca", label: "Ameca" },
      { value: "arandas", label: "Arandas" },
      { value: "tequila", label: "Tequila" },
      { value: "chapala", label: "Chapala" },
      { value: "zapotlanejo", label: "Zapotlanejo" },
      { value: "tomatlan", label: "Tomatlán" },
      { value: "autlan", label: "Autlán de Navarro" },
    ],
    mex: [
      { value: "toluca", label: "Toluca de Lerdo" },
      { value: "naucalpan", label: "Naucalpan de Juárez" },
      { value: "tlalnepantla", label: "Tlalnepantla de Baz" },
      { value: "ecatepec", label: "Ecatepec de Morelos" },
      { value: "nezahualcoyotl", label: "Nezahualcóyotl" },
      { value: "chimalhuacan", label: "Chimalhuacán" },
      { value: "cuautitlan-izcalli", label: "Cuautitlán Izcalli" },
      { value: "tultitlan", label: "Tultitlán" },
      { value: "atizapan", label: "Atizapán de Zaragoza" },
      { value: "nicolas-romero", label: "Nicolás Romero" },
      { value: "tecamac", label: "Tecámac" },
      { value: "coacalco", label: "Coacalco de Berriozábal" },
      { value: "huixquilucan", label: "Huixquilucan" },
      { value: "zumpango", label: "Zumpango" },
      { value: "chicoloapan", label: "Chicoloapan" },
      { value: "ixtapaluca", label: "Ixtapaluca" },
      { value: "valle-chalco", label: "Valle de Chalco Solidaridad" },
      { value: "teotihuacan", label: "Teotihuacán" },
      { value: "metepec", label: "Metepec" },
      { value: "lerma", label: "Lerma" },
    ],
    mich: [
      { value: "morelia", label: "Morelia" },
      { value: "zamora", label: "Zamora de Hidalgo" },
      { value: "uruapan", label: "Uruapan" },
    ],
    mor: [
      { value: "cuernavaca", label: "Cuernavaca" },
      { value: "cuautla", label: "Cuautla" },
    ],
    nay: [
      { value: "tepic", label: "Tepic" },
      { value: "bahia-banderas", label: "Bahía de Banderas" },
    ],
    nl: [
      { value: "monterrey", label: "Monterrey" },
      { value: "san-nicolas", label: "San Nicolás de los Garza" },
      { value: "guadalupe", label: "Guadalupe" },
      { value: "apodaca", label: "Apodaca" },
      { value: "santa-catarina", label: "Santa Catarina" },
      { value: "san-pedro", label: "San Pedro Garza García" },
      { value: "escobedo", label: "General Escobedo" },
      { value: "garcia", label: "García" },
      { value: "juarez", label: "Ciudad Juárez" },
      { value: "cadereyta", label: "Cadereyta Jiménez" },
      { value: "cienega-flores", label: "Ciénega de Flores" },
      { value: "el-carmen", label: "El Carmen" },
      { value: "hidalgo", label: "Hidalgo" },
      { value: "salinas-victoria", label: "Salinas Victoria" },
    ],
    oax: [
      { value: "oaxaca", label: "Oaxaca de Juárez" },
      { value: "santa-cruz", label: "Santa Cruz Xoxocotlán" },
    ],
    pue: [
      { value: "puebla", label: "Puebla de Zaragoza" },
      { value: "cholula", label: "Cholula" },
      { value: "tehuacan", label: "Tehuacán" },
      { value: "chignahuapan", label: "Chignahuapan" },
      { value: "atlixco", label: "Atlixco" },
      { value: "san-martin", label: "San Martín Texmelucan" },
      { value: "zacatlan", label: "Zacatlán" },
      { value: "teziutlan", label: "Teziutlán" },
      { value: "huejotzingo", label: "Huejotzingo" },
      { value: "san-pedro", label: "San Pedro Cholula" },
      { value: "izucar", label: "Izúcar de Matamoros" },
      { value: "tepeaca", label: "Tepeaca" },
      { value: "tlaxcala-puebla", label: "Tlaxcala" },
    ],
    qro: [
      { value: "queretaro", label: "Querétaro" },
      { value: "san-juan", label: "San Juan del Río" },
    ],
    qroo: [
      { value: "cancun", label: "Cancún" },
      { value: "chetumal", label: "Chetumal" },
      { value: "playa-del-carmen", label: "Playa del Carmen" },
    ],
    slp: [
      { value: "san-luis-potosi", label: "San Luis Potosí" },
      { value: "ciudad-valles", label: "Ciudad Valles" },
    ],
    sin: [
      { value: "culiacan", label: "Culiacán Rosales" },
      { value: "mazatlan", label: "Mazatlán" },
    ],
    son: [
      { value: "hermosillo", label: "Hermosillo" },
      { value: "ciudad-obregon", label: "Ciudad Obregón" },
      { value: "nogales", label: "Nogales" },
    ],
    tab: [
      { value: "villahermosa", label: "Villahermosa" },
      { value: "ciudad-del-carmen", label: "Ciudad del Carmen" },
    ],
    tam: [
      { value: "ciudad-victoria", label: "Ciudad Victoria" },
      { value: "reynosa", label: "Reynosa" },
      { value: "matamoros", label: "Matamoros" },
    ],
    tlx: [{ value: "tlaxcala", label: "Tlaxcala de Xicohténcatl" }],
    ver: [
      { value: "xalapa", label: "Xalapa-Enríquez" },
      { value: "veracruz", label: "Veracruz" },
      { value: "cordoba", label: "Córdoba" },
      { value: "poza-rica", label: "Poza Rica de Hidalgo" },
      { value: "coatzacoalcos", label: "Coatzacoalcos" },
      { value: "orizaba", label: "Orizaba" },
      { value: "minatitlan", label: "Minatitlán" },
      { value: "coatepec", label: "Coatepec" },
      { value: "papantla", label: "Papantla" },
      { value: "tuxpan", label: "Tuxpan" },
      { value: "martinez", label: "Martínez de la Torre" },
      { value: "alvarado", label: "Alvarado" },
      { value: "boca-del-rio", label: "Boca del Río" },
      { value: "fortin", label: "Fortín de las Flores" },
      { value: "cosamaloapan", label: "Cosamaloapan" },
    ],
    yuc: [
      { value: "merida", label: "Mérida" },
      { value: "valladolid", label: "Valladolid" },
    ],
    zac: [
      { value: "zacatecas", label: "Zacatecas" },
      { value: "fresnillo", label: "Fresnillo" },
    ],
  },
  ar: {
    ba: [
      { value: "buenos-aires", label: "Buenos Aires" },
      { value: "la-plata", label: "La Plata" },
      { value: "mar-del-plata", label: "Mar del Plata" },
      { value: "bahia-blanca", label: "Bahía Blanca" },
    ],
    cat: [{ value: "san-fernando", label: "San Fernando del Valle de Catamarca" }],
    cha: [{ value: "resistencia", label: "Resistencia" }],
    chu: [{ value: "rawson", label: "Rawson" }, { value: "comodoro-rivadavia", label: "Comodoro Rivadavia" }],
    cor: [
      { value: "cordoba", label: "Córdoba" },
      { value: "rio-cuarto", label: "Río Cuarto" },
    ],
    ctes: [{ value: "corrientes", label: "Corrientes" }],
    er: [{ value: "parana", label: "Paraná" }],
    fo: [{ value: "formosa", label: "Formosa" }],
    juj: [{ value: "san-salvador", label: "San Salvador de Jujuy" }],
    lp: [{ value: "santa-rosa", label: "Santa Rosa" }],
    lr: [{ value: "la-rioja", label: "La Rioja" }],
    men: [
      { value: "mendoza", label: "Mendoza" },
      { value: "san-rafael", label: "San Rafael" },
    ],
    mis: [{ value: "posadas", label: "Posadas" }],
    neu: [{ value: "neuquen", label: "Neuquén" }],
    rn: [{ value: "viedma", label: "Viedma" }, { value: "bariloche", label: "San Carlos de Bariloche" }],
    sal: [{ value: "salta", label: "Salta" }],
    sju: [{ value: "san-juan", label: "San Juan" }],
    sl: [{ value: "san-luis", label: "San Luis" }],
    sc: [{ value: "rio-gallegos", label: "Río Gallegos" }],
    sf: [
      { value: "santa-fe", label: "Santa Fe" },
      { value: "rosario", label: "Rosario" },
    ],
    sgo: [{ value: "santiago-del-estero", label: "Santiago del Estero" }],
    tf: [{ value: "ushuaia", label: "Ushuaia" }],
    tuc: [{ value: "san-miguel", label: "San Miguel de Tucumán" }],
  },
  co: {
    amazonas: [{ value: "leticia", label: "Leticia" }],
    antioquia: [
      { value: "medellin", label: "Medellín" },
      { value: "bello", label: "Bello" },
      { value: "itagui", label: "Itagüí" },
      { value: "envigado", label: "Envigado" },
      { value: "sabaneta", label: "Sabaneta" },
      { value: "la-estrella", label: "La Estrella" },
      { value: "caldas", label: "Caldas" },
      { value: "rionegro", label: "Rionegro" },
      { value: "girardota", label: "Girardota" },
      { value: "copacabana", label: "Copacabana" },
      { value: "barbosa", label: "Barbosa" },
      { value: "guarne", label: "Guarne" },
      { value: "santuario", label: "Santuario" },
      { value: "marinilla", label: "Marinilla" },
      { value: "el-retiro", label: "El Retiro" },
    ],
    arauca: [{ value: "arauca", label: "Arauca" }],
    atlantico: [
      { value: "barranquilla", label: "Barranquilla" },
      { value: "soledad", label: "Soledad" },
    ],
    bolivar: [
      { value: "cartagena", label: "Cartagena de Indias" },
      { value: "magangue", label: "Magangué" },
    ],
    boyaca: [
      { value: "tunja", label: "Tunja" },
      { value: "duitama", label: "Duitama" },
    ],
    caldas: [
      { value: "manizales", label: "Manizales" },
      { value: "la-dorada", label: "La Dorada" },
    ],
    caqueta: [{ value: "florencia", label: "Florencia" }],
    casanare: [{ value: "yopal", label: "Yopal" }],
    cauca: [
      { value: "popayan", label: "Popayán" },
      { value: "santander", label: "Santander de Quilichao" },
    ],
    cesar: [
      { value: "valledupar", label: "Valledupar" },
      { value: "aguachica", label: "Aguachica" },
    ],
    choco: [{ value: "quibdo", label: "Quibdó" }],
    cordoba: [
      { value: "monteria", label: "Montería" },
      { value: "sahagun", label: "Sahagún" },
    ],
    cundinamarca: [
      { value: "bogota", label: "Bogotá" },
      { value: "soacha", label: "Soacha" },
      { value: "facatativa", label: "Facatativá" },
      { value: "girardot", label: "Girardot" },
      { value: "zipaquira", label: "Zipaquirá" },
      { value: "chia", label: "Chía" },
      { value: "cajica", label: "Cajicá" },
      { value: "madrid", label: "Madrid" },
      { value: "mosquera", label: "Mosquera" },
      { value: "funza", label: "Funza" },
      { value: "sibate", label: "Sibaté" },
      { value: "fusagasuga", label: "Fusagasugá" },
      { value: "ubate", label: "Ubaté" },
      { value: "villeta", label: "Villeta" },
      { value: "guaduas", label: "Guaduas" },
    ],
    gua: [{ value: "inirida", label: "Inírida" }],
    guajira: [
      { value: "riohacha", label: "Riohacha" },
      { value: "maicao", label: "Maicao" },
    ],
    guaviare: [{ value: "san-jose", label: "San José del Guaviare" }],
    huila: [
      { value: "neiva", label: "Neiva" },
      { value: "pitalito", label: "Pitalito" },
    ],
    magdalena: [
      { value: "santa-marta", label: "Santa Marta" },
      { value: "cienaga", label: "Ciénaga" },
    ],
    meta: [
      { value: "villavicencio", label: "Villavicencio" },
      { value: "acacias", label: "Acacías" },
    ],
    narino: [
      { value: "pasto", label: "Pasto" },
      { value: "tumaco", label: "Tumaco" },
    ],
    "norte-santander": [
      { value: "cucuta", label: "Cúcuta" },
      { value: "ocaña", label: "Ocaña" },
    ],
    putumayo: [{ value: "mocoa", label: "Mocoa" }],
    quindio: [
      { value: "armenia", label: "Armenia" },
      { value: "calarca", label: "Calarcá" },
    ],
    risaralda: [
      { value: "pereira", label: "Pereira" },
      { value: "dosquebradas", label: "Dosquebradas" },
    ],
    "san-andres": [{ value: "san-andres", label: "San Andrés" }],
    santander: [
      { value: "bucaramanga", label: "Bucaramanga" },
      { value: "floridablanca", label: "Floridablanca" },
    ],
    sucre: [
      { value: "sincelejo", label: "Sincelejo" },
      { value: "corozal", label: "Corozal" },
    ],
    tolima: [
      { value: "ibague", label: "Ibagué" },
      { value: "espinal", label: "El Espinal" },
    ],
    "valle-cauca": [
      { value: "cali", label: "Cali" },
      { value: "palmira", label: "Palmira" },
      { value: "buenaventura", label: "Buenaventura" },
      { value: "tulua", label: "Tuluá" },
      { value: "cartago", label: "Cartago" },
      { value: "buga", label: "Buga" },
      { value: "yumbo", label: "Yumbo" },
      { value: "ginebra", label: "Ginebra" },
      { value: "guacari", label: "Guacarí" },
      { value: "ginebra", label: "Ginebra" },
      { value: "cerrito", label: "El Cerrito" },
      { value: "vijes", label: "Vijes" },
      { value: "yotoco", label: "Yotoco" },
      { value: "restrepo", label: "Restrepo" },
      { value: "darien", label: "Darién" },
    ],
    vaupes: [{ value: "mitu", label: "Mitú" }],
    vichada: [{ value: "puerto-carreno", label: "Puerto Carreño" }],
  },
  cl: {
    "arica-parinacota": [{ value: "arica", label: "Arica" }],
    tarapaca: [{ value: "iquique", label: "Iquique" }],
    antofagasta: [
      { value: "antofagasta", label: "Antofagasta" },
      { value: "calama", label: "Calama" },
    ],
    atacama: [
      { value: "copiapo", label: "Copiapó" },
      { value: "vallenar", label: "Vallenar" },
    ],
    coquimbo: [
      { value: "la-serena", label: "La Serena" },
      { value: "coquimbo", label: "Coquimbo" },
    ],
    valparaiso: [
      { value: "valparaiso", label: "Valparaíso" },
      { value: "vina-del-mar", label: "Viña del Mar" },
      { value: "quillota", label: "Quillota" },
    ],
    metropolitana: [
      { value: "santiago", label: "Santiago" },
      { value: "puente-alto", label: "Puente Alto" },
      { value: "maipu", label: "Maipú" },
      { value: "san-bernardo", label: "San Bernardo" },
      { value: "la-florida", label: "La Florida" },
      { value: "penalolen", label: "Peñalolén" },
      { value: "las-condes", label: "Las Condes" },
      { value: "providencia", label: "Providencia" },
      { value: "nunoa", label: "Ñuñoa" },
      { value: "recoleta", label: "Recoleta" },
      { value: "independencia", label: "Independencia" },
      { value: "conchali", label: "Conchalí" },
      { value: "renca", label: "Renca" },
      { value: "cerro-navia", label: "Cerro Navia" },
      { value: "lo-prado", label: "Lo Prado" },
      { value: "quilicura", label: "Quilicura" },
      { value: "colina", label: "Colina" },
      { value: "lampa", label: "Lampa" },
      { value: "tiltil", label: "Tiltil" },
      { value: "pudahuel", label: "Pudahuel" },
    ],
    ohiggins: [
      { value: "rancagua", label: "Rancagua" },
      { value: "san-fernando", label: "San Fernando" },
    ],
    maule: [
      { value: "talca", label: "Talca" },
      { value: "curico", label: "Curicó" },
    ],
    nuble: [
      { value: "chillan", label: "Chillán" },
      { value: "san-carlos", label: "San Carlos" },
    ],
    biobio: [
      { value: "concepcion", label: "Concepción" },
      { value: "los-angeles", label: "Los Ángeles" },
    ],
    araucania: [
      { value: "temuco", label: "Temuco" },
      { value: "villarrica", label: "Villarrica" },
    ],
    "los-rios": [
      { value: "valdivia", label: "Valdivia" },
      { value: "osorno", label: "Osorno" },
    ],
    "los-lagos": [
      { value: "puerto-montt", label: "Puerto Montt" },
      { value: "castro", label: "Castro" },
    ],
    aysen: [{ value: "coyhaique", label: "Coyhaique" }],
    magallanes: [
      { value: "punta-arenas", label: "Punta Arenas" },
      { value: "puerto-natales", label: "Puerto Natales" },
    ],
  },
  pe: {
    amazonas: [{ value: "chachapoyas", label: "Chachapoyas" }],
    ancash: [
      { value: "huaraz", label: "Huaraz" },
      { value: "chimbote", label: "Chimbote" },
      { value: "caraz", label: "Caraz" },
    ],
    apurimac: [
      { value: "abancay", label: "Abancay" },
      { value: "andahuaylas", label: "Andahuaylas" },
    ],
    arequipa: [
      { value: "arequipa", label: "Arequipa" },
      { value: "cerro-verde", label: "Cerro Verde" },
      { value: "mollendo", label: "Mollendo" },
    ],
    ayacucho: [
      { value: "ayacucho", label: "Ayacucho" },
      { value: "huanta", label: "Huanta" },
    ],
    cajamarca: [
      { value: "cajamarca", label: "Cajamarca" },
      { value: "jaen", label: "Jaén" },
      { value: "cutervo", label: "Cutervo" },
    ],
    callao: [{ value: "callao", label: "Callao" }],
    cusco: [
      { value: "cusco", label: "Cusco" },
      { value: "sicuani", label: "Sicuani" },
      { value: "quillabamba", label: "Quillabamba" },
    ],
    huancavelica: [{ value: "huancavelica", label: "Huancavelica" }],
    huanuco: [
      { value: "huanuco", label: "Huánuco" },
      { value: "tingo-maria", label: "Tingo María" },
    ],
    ica: [
      { value: "ica", label: "Ica" },
      { value: "chincha-alta", label: "Chincha Alta" },
      { value: "pisco", label: "Pisco" },
    ],
    junin: [
      { value: "huancayo", label: "Huancayo" },
      { value: "jauja", label: "Jauja" },
      { value: "tarma", label: "Tarma" },
    ],
    "la-libertad": [
      { value: "trujillo", label: "Trujillo" },
      { value: "chimbote", label: "Chimbote" },
      { value: "huamachuco", label: "Huamachuco" },
    ],
    lambayeque: [
      { value: "chiclayo", label: "Chiclayo" },
      { value: "lambayeque", label: "Lambayeque" },
      { value: "ferreñafe", label: "Ferreñafe" },
    ],
    lima: [
      { value: "lima", label: "Lima" },
      { value: "huacho", label: "Huacho" },
      { value: "cañete", label: "Cañete" },
      { value: "barranca", label: "Barranca" },
    ],
    loreto: [
      { value: "iquitos", label: "Iquitos" },
      { value: "yurimaguas", label: "Yurimaguas" },
    ],
    "madre-de-dios": [{ value: "puerto-maldonado", label: "Puerto Maldonado" }],
    moquegua: [
      { value: "moquegua", label: "Moquegua" },
      { value: "ilo", label: "Ilo" },
    ],
    pasco: [{ value: "cerro-de-pasco", label: "Cerro de Pasco" }],
    piura: [
      { value: "piura", label: "Piura" },
      { value: "sullana", label: "Sullana" },
      { value: "talara", label: "Talara" },
    ],
    puno: [
      { value: "puno", label: "Puno" },
      { value: "juliaca", label: "Juliaca" },
    ],
    "san-martin": [
      { value: "moyobamba", label: "Moyobamba" },
      { value: "tarapoto", label: "Tarapoto" },
    ],
    tacna: [{ value: "tacna", label: "Tacna" }],
    tumbes: [{ value: "tumbes", label: "Tumbes" }],
    ucayali: [
      { value: "pucallpa", label: "Pucallpa" },
      { value: "contamana", label: "Contamana" },
    ],
  },
  ve: {
    amazonas: [{ value: "puerto-ayacucho", label: "Puerto Ayacucho" }],
    anzategui: [
      { value: "barcelona", label: "Barcelona" },
      { value: "puerto-la-cruz", label: "Puerto La Cruz" },
      { value: "el-tigre", label: "El Tigre" },
    ],
    apure: [
      { value: "san-fernando", label: "San Fernando de Apure" },
      { value: "guasdualito", label: "Guasdualito" },
    ],
    aragua: [
      { value: "maracay", label: "Maracay" },
      { value: "turmero", label: "Turmero" },
      { value: "la-victoria", label: "La Victoria" },
    ],
    barinas: [{ value: "barinas", label: "Barinas" }],
    bolivar: [
      { value: "ciudad-bolivar", label: "Ciudad Bolívar" },
      { value: "ciudad-guayana", label: "Ciudad Guayana" },
    ],
    carabobo: [
      { value: "valencia", label: "Valencia" },
      { value: "puerto-cabello", label: "Puerto Cabello" },
      { value: "guacara", label: "Guacara" },
    ],
    cojedes: [{ value: "san-carlos", label: "San Carlos" }],
    "delta-amacuro": [{ value: "tucupita", label: "Tucupita" }],
    "distrito-capital": [{ value: "caracas", label: "Caracas" }],
    falcon: [
      { value: "coro", label: "Coro" },
      { value: "punto-fijo", label: "Punto Fijo" },
    ],
    guarico: [
      { value: "san-juan-los-morros", label: "San Juan de los Morros" },
      { value: "calabozo", label: "Calabozo" },
    ],
    lara: [
      { value: "barquisimeto", label: "Barquisimeto" },
      { value: "cabudare", label: "Cabudare" },
    ],
    merida: [
      { value: "merida", label: "Mérida" },
      { value: "el-vigia", label: "El Vigía" },
    ],
    miranda: [
      { value: "los-teques", label: "Los Teques" },
      { value: "guarenas", label: "Guarenas" },
      { value: "guatire", label: "Guatire" },
    ],
    monagas: [
      { value: "maturin", label: "Maturín" },
      { value: "caripito", label: "Caripito" },
    ],
    "nueva-esparta": [{ value: "la-asuncion", label: "La Asunción" }],
    portuguesa: [
      { value: "guanare", label: "Guanare" },
      { value: "acarigua", label: "Acarigua" },
    ],
    sucre: [
      { value: "cumana", label: "Cumaná" },
      { value: "carupano", label: "Carúpano" },
    ],
    tachira: [
      { value: "san-cristobal", label: "San Cristóbal" },
      { value: "rubio", label: "Rubio" },
    ],
    trujillo: [{ value: "trujillo", label: "Trujillo" }],
    vargas: [{ value: "la-guaira", label: "La Guaira" }],
    yaracuy: [{ value: "san-felipe", label: "San Felipe" }],
    zulia: [
      { value: "maracaibo", label: "Maracaibo" },
      { value: "cabimas", label: "Cabimas" },
      { value: "ciudad-ojeda", label: "Ciudad Ojeda" },
    ],
  },
  ec: {
    azuay: [
      { value: "cuenca", label: "Cuenca" },
      { value: "gualaceo", label: "Gualaceo" },
    ],
    bolivar: [{ value: "guaranda", label: "Guaranda" }],
    canar: [{ value: "azogues", label: "Azogues" }],
    carchi: [{ value: "tulcan", label: "Tulcán" }],
    chimborazo: [
      { value: "riobamba", label: "Riobamba" },
      { value: "guaranda", label: "Guaranda" },
    ],
    cotopaxi: [
      { value: "latacunga", label: "Latacunga" },
      { value: "saquisili", label: "Saquisilí" },
    ],
    "el-oro": [
      { value: "machala", label: "Machala" },
      { value: "santa-rosa", label: "Santa Rosa" },
    ],
    esmeraldas: [
      { value: "esmeraldas", label: "Esmeraldas" },
      { value: "atacames", label: "Atacames" },
    ],
    galapagos: [{ value: "puerto-baquerizo", label: "Puerto Baquerizo Moreno" }],
    guayas: [
      { value: "guayaquil", label: "Guayaquil" },
      { value: "samborondon", label: "Samborondón" },
      { value: "durán", label: "Durán" },
    ],
    imbabura: [
      { value: "ibalra", label: "Ibarra" },
      { value: "otavalo", label: "Otavalo" },
    ],
    loja: [
      { value: "loja", label: "Loja" },
      { value: "catamayo", label: "Catamayo" },
    ],
    "los-rios": [
      { value: "babahoyo", label: "Babahoyo" },
      { value: "quevedo", label: "Quevedo" },
    ],
    manabi: [
      { value: "portoviejo", label: "Portoviejo" },
      { value: "manta", label: "Manta" },
      { value: "bahia", label: "Bahía de Caráquez" },
    ],
    "morona-santiago": [{ value: "macas", label: "Macas" }],
    napo: [{ value: "tena", label: "Tena" }],
    orellana: [{ value: "francisco-orellana", label: "Francisco de Orellana" }],
    pastaza: [{ value: "puyo", label: "Puyo" }],
    pichincha: [
      { value: "quito", label: "Quito" },
      { value: "sangolqui", label: "Sangolquí" },
      { value: "cayambe", label: "Cayambe" },
    ],
    "santa-elena": [
      { value: "santa-elena", label: "Santa Elena" },
      { value: "salinas", label: "Salinas" },
    ],
    "santo-domingo": [{ value: "santo-domingo", label: "Santo Domingo de los Colorados" }],
    sucumbios: [{ value: "nueva-loja", label: "Nueva Loja" }],
    tungurahua: [
      { value: "ambato", label: "Ambato" },
      { value: "pelileo", label: "Pelileo" },
    ],
    "zamora-chinchipe": [{ value: "zamora", label: "Zamora" }],
  },
  gt: {
    "alta-verapaz": [
      { value: "coban", label: "Cobán" },
      { value: "san-pedro-carcha", label: "San Pedro Carchá" },
    ],
    "baja-verapaz": [{ value: "salamá", label: "Salamá" }],
    chimaltenango: [
      { value: "chimaltenango", label: "Chimaltenango" },
      { value: "tepan", label: "Tepán" },
    ],
    chiquimula: [{ value: "chiquimula", label: "Chiquimula" }],
    "el-progreso": [{ value: "guastatoya", label: "Guastatoya" }],
    escuintla: [
      { value: "escuintla", label: "Escuintla" },
      { value: "santa-lucia-cotzumalguapa", label: "Santa Lucía Cotzumalguapa" },
    ],
    guatemala: [
      { value: "ciudad-guatemala", label: "Ciudad de Guatemala" },
      { value: "mixco", label: "Mixco" },
      { value: "villa-nueva", label: "Villa Nueva" },
    ],
    huehuetenango: [
      { value: "huehuetenango", label: "Huehuetenango" },
      { value: "la-democracia", label: "La Democracia" },
    ],
    izabal: [
      { value: "puerto-barios", label: "Puerto Barrios" },
      { value: "livingston", label: "Livingston" },
    ],
    jalapa: [{ value: "jalapa", label: "Jalapa" }],
    jutiapa: [{ value: "jutiapa", label: "Jutiapa" }],
    peten: [
      { value: "flores", label: "Flores" },
      { value: "san-benito", label: "San Benito" },
    ],
    quetzaltenango: [
      { value: "quetzaltenango", label: "Quetzaltenango" },
      { value: "salcaja", label: "Salcajá" },
    ],
    quiche: [
      { value: "santa-cruz-quiche", label: "Santa Cruz del Quiché" },
      { value: "chichicastenango", label: "Chichicastenango" },
    ],
    retalhuleu: [{ value: "retalhuleu", label: "Retalhuleu" }],
    sacatepequez: [
      { value: "antigua-guatemala", label: "Antigua Guatemala" },
      { value: "ciudad-vieja", label: "Ciudad Vieja" },
    ],
    "san-marcos": [{ value: "san-marcos", label: "San Marcos" }],
    "santa-rosa": [{ value: "cuilapa", label: "Cuilapa" }],
    solola: [
      { value: "solola", label: "Sololá" },
      { value: "panajachel", label: "Panajachel" },
    ],
    suchitepequez: [
      { value: "mazatenango", label: "Mazatenango" },
      { value: "chicacao", label: "Chicacao" },
    ],
    totonicapan: [{ value: "totonicapan", label: "Totonicapán" }],
    zacapa: [{ value: "zacapa", label: "Zacapa" }],
  },
  cu: {
    artemisa: [
      { value: "artemisa", label: "Artemisa" },
      { value: "san-antonio", label: "San Antonio de los Baños" },
    ],
    camaguey: [
      { value: "camaguey", label: "Camagüey" },
      { value: "florida", label: "Florida" },
    ],
    "ciego-avila": [
      { value: "ciego-avila", label: "Ciego de Ávila" },
      { value: "moron", label: "Morón" },
    ],
    cienfuegos: [{ value: "cienfuegos", label: "Cienfuegos" }],
    granma: [
      { value: "bayamo", label: "Bayamo" },
      { value: "manzanillo", label: "Manzanillo" },
    ],
    guantanamo: [
      { value: "guantanamo", label: "Guantánamo" },
      { value: "baracoa", label: "Baracoa" },
    ],
    holguin: [
      { value: "holguin", label: "Holguín" },
      { value: "banes", label: "Banes" },
    ],
    "isla-juventud": [{ value: "nueva-gerona", label: "Nueva Gerona" }],
    "la-habana": [
      { value: "la-habana", label: "La Habana" },
      { value: "centro-habana", label: "Centro Habana" },
      { value: "vedado", label: "Vedado" },
    ],
    "las-tunas": [{ value: "las-tunas", label: "Las Tunas" }],
    matanzas: [
      { value: "matanzas", label: "Matanzas" },
      { value: "cardenas", label: "Cárdenas" },
    ],
    mayabeque: [{ value: "san-jose-lajas", label: "San José de las Lajas" }],
    "pinar-del-rio": [
      { value: "pinar-del-rio", label: "Pinar del Río" },
      { value: "consolacion-sur", label: "Consolación del Sur" },
    ],
    "sancti-spiritus": [{ value: "sancti-spiritus", label: "Sancti Spíritus" }],
    "santiago-cuba": [
      { value: "santiago-cuba", label: "Santiago de Cuba" },
      { value: "san-luis", label: "San Luis" },
    ],
    "villa-clara": [
      { value: "santa-clara", label: "Santa Clara" },
      { value: "placetas", label: "Placetas" },
    ],
  },
  do: {
    azua: [{ value: "azua", label: "Azua" }],
    baoruco: [{ value: "neiba", label: "Neiba" }],
    barahona: [{ value: "barahona", label: "Barahona" }],
    dajabon: [{ value: "dajabon", label: "Dajabón" }],
    "distrito-nacional": [{ value: "santo-domingo", label: "Santo Domingo" }],
    duarte: [
      { value: "san-francisco-macoris", label: "San Francisco de Macorís" },
      { value: "villa-riva", label: "Villa Riva" },
    ],
    espailat: [
      { value: "moca", label: "Moca" },
      { value: "gaspar-hernandez", label: "Gaspar Hernández" },
    ],
    "hato-mayor": [{ value: "hato-mayor", label: "Hato Mayor" }],
    "hermanas-mirabal": [{ value: "salcedo", label: "Salcedo" }],
    independencia: [{ value: "jimani", label: "Jimaní" }],
    "la-altagracia": [
      { value: "higuey", label: "Higüey" },
      { value: "punta-cana", label: "Punta Cana" },
    ],
    "la-romana": [
      { value: "la-romana", label: "La Romana" },
      { value: "bayahibe", label: "Bayahibe" },
    ],
    "la-vega": [
      { value: "la-vega", label: "La Vega" },
      { value: "jarabacoa", label: "Jarabacoa" },
    ],
    "maria-trinidad-sanchez": [{ value: "nagua", label: "Nagua" }],
    "monsenor-nouel": [{ value: "bonao", label: "Bonao" }],
    "monte-cristi": [{ value: "monte-cristi", label: "Monte Cristi" }],
    "monte-plata": [{ value: "monte-plata", label: "Monte Plata" }],
    pedernales: [{ value: "pedernales", label: "Pedernales" }],
    peravia: [
      { value: "bani", label: "Baní" },
      { value: "nizao", label: "Nizao" },
    ],
    "puerto-plata": [
      { value: "puerto-plata", label: "Puerto Plata" },
      { value: "sosua", label: "Sosúa" },
    ],
    samana: [
      { value: "samana", label: "Samaná" },
      { value: "las-terrenas", label: "Las Terrenas" },
    ],
    "san-cristobal": [
      { value: "san-cristobal", label: "San Cristóbal" },
      { value: "villa-altagracia", label: "Villa Altagracia" },
    ],
    "san-jose-ooa": [{ value: "san-jose-ooa", label: "San José de Ocoa" }],
    "san-juan": [{ value: "san-juan", label: "San Juan" }],
    "san-pedro-macoris": [
      { value: "san-pedro-macoris", label: "San Pedro de Macorís" },
      { value: "los-llanos", label: "Los Llanos" },
    ],
    "sanchez-ramirez": [{ value: "cotui", label: "Cotui" }],
    santiago: [
      { value: "santiago", label: "Santiago" },
      { value: "villa-gonzalez", label: "Villa González" },
    ],
    "santiago-rodriguez": [{ value: "san-ignacio-sabaneta", label: "San Ignacio de Sabaneta" }],
    "santo-domingo": [
      { value: "santo-domingo-este", label: "Santo Domingo Este" },
      { value: "santo-domingo-norte", label: "Santo Domingo Norte" },
    ],
    valverde: [{ value: "mao", label: "Mao" }],
  },
  hn: {
    atlantida: [
      { value: "la-ceiba", label: "La Ceiba" },
      { value: "tela", label: "Tela" },
    ],
    choluteca: [
      { value: "choluteca", label: "Choluteca" },
      { value: "san-lorenzo", label: "San Lorenzo" },
    ],
    colon: [
      { value: "trujillo", label: "Trujillo" },
      { value: "tocoa", label: "Tocoa" },
    ],
    comayagua: [
      { value: "comayagua", label: "Comayagua" },
      { value: "siguatepeque", label: "Siguatepeque" },
    ],
    copan: [
      { value: "santa-rosa-copan", label: "Santa Rosa de Copán" },
      { value: "copan-ruinas", label: "Copán Ruinas" },
    ],
    cortes: [
      { value: "san-pedro-sula", label: "San Pedro Sula" },
      { value: "puerto-cortes", label: "Puerto Cortés" },
    ],
    "el-paraiso": [
      { value: "yuscaran", label: "Yuscarán" },
      { value: "danli", label: "Danlí" },
    ],
    "francisco-morazan": [
      { value: "tegucigalpa", label: "Tegucigalpa" },
      { value: "comayaguela", label: "Comayagüela" },
    ],
    "gracias-dios": [{ value: "puerto-lempira", label: "Puerto Lempira" }],
    intibuca: [{ value: "la-esperanza", label: "La Esperanza" }],
    "islas-bahia": [{ value: "roatan", label: "Roatán" }],
    "la-paz": [{ value: "la-paz", label: "La Paz" }],
    lempira: [{ value: "gracias", label: "Gracias" }],
    ocotepeque: [{ value: "nueva-ocotepeque", label: "Nueva Ocotepeque" }],
    olancho: [
      { value: "juticalpa", label: "Juticalpa" },
      { value: "catacamas", label: "Catacamas" },
    ],
    "santa-barbara": [{ value: "santa-barbara", label: "Santa Bárbara" }],
    valle: [{ value: "nacaome", label: "Nacaome" }],
    yoro: [
      { value: "yoro", label: "Yoro" },
      { value: "el-progreso", label: "El Progreso" },
    ],
  },
  sv: {
    ahuachapan: [{ value: "ahuachapan", label: "Ahuachapán" }],
    cabanas: [{ value: "sensuntepeque", label: "Sensuntepeque" }],
    chalatenango: [{ value: "chalatenango", label: "Chalatenango" }],
    cuscatlan: [{ value: "cojutepeque", label: "Cojutepeque" }],
    "la-libertad": [
      { value: "santa-tecla", label: "Santa Tecla" },
      { value: "antiguo-cuscatlan", label: "Antiguo Cuscatlán" },
    ],
    "la-paz": [{ value: "zacatecoluca", label: "Zacatecoluca" }],
    "la-union": [{ value: "la-union", label: "La Unión" }],
    morazan: [{ value: "san-francisco-gotera", label: "San Francisco Gotera" }],
    "san-miguel": [
      { value: "san-miguel", label: "San Miguel" },
      { value: "ciudad-barrios", label: "Ciudad Barrios" },
    ],
    "san-salvador": [
      { value: "san-salvador", label: "San Salvador" },
      { value: "soyapango", label: "Soyapango" },
      { value: "apopa", label: "Apopa" },
    ],
    "san-vicente": [{ value: "san-vicente", label: "San Vicente" }],
    "santa-ana": [
      { value: "santa-ana", label: "Santa Ana" },
      { value: "metapan", label: "Metapán" },
    ],
    sonsonate: [
      { value: "sonsonate", label: "Sonsonate" },
      { value: "acajutla", label: "Acajutla" },
    ],
    usulutan: [{ value: "usulutan", label: "Usulután" }],
  },
  ni: {
    boaco: [{ value: "boaco", label: "Boaco" }],
    carazo: [{ value: "jinotepe", label: "Jinotepe" }],
    chinandega: [
      { value: "chinandega", label: "Chinandega" },
      { value: "corinto", label: "Corinto" },
    ],
    chontales: [{ value: "juigalpa", label: "Juigalpa" }],
    esteli: [{ value: "esteli", label: "Estelí" }],
    granada: [{ value: "granada", label: "Granada" }],
    jinotega: [{ value: "jinotega", label: "Jinotega" }],
    leon: [
      { value: "leon", label: "León" },
      { value: "la-paz-centro", label: "La Paz Centro" },
    ],
    madriz: [{ value: "somoto", label: "Somoto" }],
    managua: [
      { value: "managua", label: "Managua" },
      { value: "ciudad-sandino", label: "Ciudad Sandino" },
    ],
    masaya: [
      { value: "masaya", label: "Masaya" },
      { value: "catarina", label: "Catarina" },
    ],
    matagalpa: [
      { value: "matagalpa", label: "Matagalpa" },
      { value: "sebaco", label: "Sebaco" },
    ],
    "nueva-segovia": [{ value: "ocotal", label: "Ocotal" }],
    "rio-san-juan": [{ value: "san-carlos", label: "San Carlos" }],
    rivas: [
      { value: "rivas", label: "Rivas" },
      { value: "san-jorge", label: "San Jorge" },
    ],
    "costa-caribe-norte": [{ value: "puerto-cabezas", label: "Puerto Cabezas" }],
    "costa-caribe-sur": [{ value: "bluefields", label: "Bluefields" }],
  },
  cr: {
    alajuela: [
      { value: "alajuela", label: "Alajuela" },
      { value: "san-ramon", label: "San Ramón" },
    ],
    cartago: [
      { value: "cartago", label: "Cartago" },
      { value: "paraiso", label: "Paraíso" },
    ],
    guanacaste: [
      { value: "liberia", label: "Liberia" },
      { value: "nicoya", label: "Nicoya" },
    ],
    heredia: [
      { value: "heredia", label: "Heredia" },
      { value: "san-rafael", label: "San Rafael" },
    ],
    limon: [
      { value: "limon", label: "Limón" },
      { value: "puerto-limon", label: "Puerto Limón" },
    ],
    puntarenas: [
      { value: "puntarenas", label: "Puntarenas" },
      { value: "golfito", label: "Golfito" },
    ],
    "san-jose": [
      { value: "san-jose", label: "San José" },
      { value: "escazu", label: "Escazú" },
      { value: "desamparados", label: "Desamparados" },
    ],
  },
  pa: {
    "bocas-del-toro": [{ value: "bocas-del-toro", label: "Bocas del Toro" }],
    chiriqui: [
      { value: "david", label: "David" },
      { value: "puerto-armuelles", label: "Puerto Armuelles" },
    ],
    cocle: [
      { value: "penonome", label: "Penonomé" },
      { value: "aguadulce", label: "Aguadulce" },
    ],
    colon: [
      { value: "colon", label: "Colón" },
      { value: "cristobal", label: "Cristóbal" },
    ],
    darien: [{ value: "la-palma", label: "La Palma" }],
    herrera: [{ value: "chitre", label: "Chitré" }],
    "los-santos": [{ value: "las-tablas", label: "Las Tablas" }],
    panama: [
      { value: "ciudad-panama", label: "Ciudad de Panamá" },
      { value: "san-miguelito", label: "San Miguelito" },
    ],
    "panama-oeste": [
      { value: "la-chorrera", label: "La Chorrera" },
      { value: "arraijan", label: "Arraiján" },
    ],
    veraguas: [{ value: "santiago", label: "Santiago" }],
    "guna-yala": [{ value: "el-porvenir", label: "El Porvenir" }],
    "embera-wounaan": [{ value: "union-choco", label: "Unión Chocó" }],
    "ngabe-bugle": [{ value: "llano-tugri", label: "Llano Tugrí" }],
  },
  py: {
    asuncion: [{ value: "asuncion", label: "Asunción" }],
    "alto-parana": [
      { value: "ciudad-del-este", label: "Ciudad del Este" },
      { value: "hernandarias", label: "Hernandarias" },
    ],
    amambay: [{ value: "pedro-juan-caballero", label: "Pedro Juan Caballero" }],
    boqueron: [{ value: "filadelfia", label: "Filadelfia" }],
    caaguazu: [{ value: "coronel-oviedo", label: "Coronel Oviedo" }],
    caazapa: [{ value: "caazapa", label: "Caazapá" }],
    canindeyu: [{ value: "salto-del-guaira", label: "Salto del Guairá" }],
    central: [
      { value: "san-lorenzo", label: "San Lorenzo" },
      { value: "fernando-de-la-mora", label: "Fernando de la Mora" },
    ],
    concepcion: [{ value: "concepcion", label: "Concepción" }],
    cordillera: [{ value: "caacupe", label: "Caacupé" }],
    guaira: [{ value: "villarrica", label: "Villarrica" }],
    itapua: [
      { value: "encarnacion", label: "Encarnación" },
      { value: "carmen-del-parana", label: "Carmen del Paraná" },
    ],
    misiones: [{ value: "san-juan-bautista", label: "San Juan Bautista" }],
    neembucu: [{ value: "pilar", label: "Pilar" }],
    paraguari: [{ value: "paraguari", label: "Paraguarí" }],
    "presidente-hayes": [{ value: "villa-hayes", label: "Villa Hayes" }],
    "san-pedro": [{ value: "san-pedro", label: "San Pedro" }],
    "alto-paraguay": [{ value: "fuerte-olimpo", label: "Fuerte Olimpo" }],
  },
  uy: {
    artigas: [{ value: "artigas", label: "Artigas" }],
    canelones: [
      { value: "canelones", label: "Canelones" },
      { value: "las-piedras", label: "Las Piedras" },
    ],
    "cerro-largo": [{ value: "melo", label: "Melo" }],
    colonia: [
      { value: "colonia-del-sacramento", label: "Colonia del Sacramento" },
      { value: "carmelo", label: "Carmelo" },
    ],
    durazno: [{ value: "durazno", label: "Durazno" }],
    flores: [{ value: "trinidad", label: "Trinidad" }],
    florida: [{ value: "florida", label: "Florida" }],
    lavalleja: [{ value: "minas", label: "Minas" }],
    maldonado: [
      { value: "maldonado", label: "Maldonado" },
      { value: "punta-del-este", label: "Punta del Este" },
    ],
    montevideo: [{ value: "montevideo", label: "Montevideo" }],
    paysandu: [{ value: "paysandu", label: "Paysandú" }],
    "rio-negro": [{ value: "fray-bentos", label: "Fray Bentos" }],
    rivera: [{ value: "rivera", label: "Rivera" }],
    rocha: [
      { value: "rocha", label: "Rocha" },
      { value: "chuy", label: "Chuy" },
    ],
    salto: [{ value: "salto", label: "Salto" }],
    "san-jose": [{ value: "san-jose-mayo", label: "San José de Mayo" }],
    soriano: [{ value: "mercedes", label: "Mercedes" }],
    tacuarembo: [{ value: "tacuarembo", label: "Tacuarembó" }],
    "treinta-tres": [{ value: "treinta-tres", label: "Treinta y Tres" }],
  },
  bo: {
    chuquisaca: [{ value: "sucre", label: "Sucre" }],
    cochabamba: [
      { value: "cochabamba", label: "Cochabamba" },
      { value: "quillacollo", label: "Quillacollo" },
    ],
    beni: [{ value: "trinidad", label: "Trinidad" }],
    "la-paz": [
      { value: "la-paz", label: "La Paz" },
      { value: "el-alto", label: "El Alto" },
    ],
    oruro: [{ value: "oruro", label: "Oruro" }],
    pando: [{ value: "cobija", label: "Cobija" }],
    potosi: [{ value: "potosi", label: "Potosí" }],
    "santa-cruz": [
      { value: "santa-cruz", label: "Santa Cruz de la Sierra" },
      { value: "montero", label: "Montero" },
    ],
    tarija: [{ value: "tarija", label: "Tarija" }],
  },
  pr: {
    aguadilla: [{ value: "aguadilla", label: "Aguadilla" }],
    arecibo: [{ value: "arecibo", label: "Arecibo" }],
    bayamon: [{ value: "bayamon", label: "Bayamón" }],
    carolina: [{ value: "carolina", label: "Carolina" }],
    caguas: [{ value: "caguas", label: "Caguas" }],
    mayaguez: [{ value: "mayaguez", label: "Mayagüez" }],
    ponce: [{ value: "ponce", label: "Ponce" }],
    "san-juan": [{ value: "san-juan", label: "San Juan" }],
  },
  us: {
    alabama: [
      { value: "birmingham", label: "Birmingham" },
      { value: "montgomery", label: "Montgomery" },
      { value: "mobile", label: "Mobile" },
    ],
    alaska: [
      { value: "anchorage", label: "Anchorage" },
      { value: "fairbanks", label: "Fairbanks" },
    ],
    arizona: [
      { value: "phoenix", label: "Phoenix" },
      { value: "tucson", label: "Tucson" },
      { value: "mesa", label: "Mesa" },
    ],
    arkansas: [
      { value: "little-rock", label: "Little Rock" },
      { value: "fort-smith", label: "Fort Smith" },
    ],
    california: [
      { value: "los-angeles", label: "Los Angeles" },
      { value: "san-diego", label: "San Diego" },
      { value: "san-jose", label: "San Jose" },
      { value: "san-francisco", label: "San Francisco" },
      { value: "fresno", label: "Fresno" },
      { value: "sacramento", label: "Sacramento" },
      { value: "long-beach", label: "Long Beach" },
      { value: "oakland", label: "Oakland" },
    ],
    colorado: [
      { value: "denver", label: "Denver" },
      { value: "colorado-springs", label: "Colorado Springs" },
      { value: "aurora", label: "Aurora" },
    ],
    connecticut: [
      { value: "bridgeport", label: "Bridgeport" },
      { value: "new-haven", label: "New Haven" },
      { value: "hartford", label: "Hartford" },
    ],
    delaware: [
      { value: "wilmington", label: "Wilmington" },
      { value: "dover", label: "Dover" },
    ],
    florida: [
      { value: "miami", label: "Miami" },
      { value: "tampa", label: "Tampa" },
      { value: "orlando", label: "Orlando" },
      { value: "jacksonville", label: "Jacksonville" },
      { value: "fort-lauderdale", label: "Fort Lauderdale" },
    ],
    georgia: [
      { value: "atlanta", label: "Atlanta" },
      { value: "augusta", label: "Augusta" },
      { value: "columbus", label: "Columbus" },
    ],
    hawaii: [
      { value: "honolulu", label: "Honolulu" },
      { value: "hilo", label: "Hilo" },
    ],
    idaho: [
      { value: "boise", label: "Boise" },
      { value: "nampa", label: "Nampa" },
    ],
    illinois: [
      { value: "chicago", label: "Chicago" },
      { value: "aurora", label: "Aurora" },
      { value: "rockford", label: "Rockford" },
    ],
    indiana: [
      { value: "indianapolis", label: "Indianapolis" },
      { value: "fort-wayne", label: "Fort Wayne" },
    ],
    iowa: [
      { value: "des-moines", label: "Des Moines" },
      { value: "cedar-rapids", label: "Cedar Rapids" },
    ],
    kansas: [
      { value: "wichita", label: "Wichita" },
      { value: "overland-park", label: "Overland Park" },
    ],
    kentucky: [
      { value: "louisville", label: "Louisville" },
      { value: "lexington", label: "Lexington" },
    ],
    louisiana: [
      { value: "new-orleans", label: "New Orleans" },
      { value: "baton-rouge", label: "Baton Rouge" },
      { value: "shreveport", label: "Shreveport" },
    ],
    maine: [
      { value: "portland", label: "Portland" },
      { value: "lewiston", label: "Lewiston" },
    ],
    maryland: [
      { value: "baltimore", label: "Baltimore" },
      { value: "frederick", label: "Frederick" },
    ],
    massachusetts: [
      { value: "boston", label: "Boston" },
      { value: "worcester", label: "Worcester" },
      { value: "springfield", label: "Springfield" },
    ],
    michigan: [
      { value: "detroit", label: "Detroit" },
      { value: "grand-rapids", label: "Grand Rapids" },
      { value: "warren", label: "Warren" },
    ],
    minnesota: [
      { value: "minneapolis", label: "Minneapolis" },
      { value: "saint-paul", label: "Saint Paul" },
    ],
    mississippi: [
      { value: "jackson", label: "Jackson" },
      { value: "gulfport", label: "Gulfport" },
    ],
    missouri: [
      { value: "kansas-city", label: "Kansas City" },
      { value: "saint-louis", label: "Saint Louis" },
      { value: "springfield", label: "Springfield" },
    ],
    montana: [
      { value: "billings", label: "Billings" },
      { value: "missoula", label: "Missoula" },
    ],
    nebraska: [
      { value: "omaha", label: "Omaha" },
      { value: "lincoln", label: "Lincoln" },
    ],
    nevada: [
      { value: "las-vegas", label: "Las Vegas" },
      { value: "henderson", label: "Henderson" },
      { value: "reno", label: "Reno" },
    ],
    "new-hampshire": [
      { value: "manchester", label: "Manchester" },
      { value: "nashua", label: "Nashua" },
    ],
    "new-jersey": [
      { value: "newark", label: "Newark" },
      { value: "jersey-city", label: "Jersey City" },
      { value: "paterson", label: "Paterson" },
    ],
    "new-mexico": [
      { value: "albuquerque", label: "Albuquerque" },
      { value: "las-cruces", label: "Las Cruces" },
    ],
    "new-york": [
      { value: "new-york", label: "New York" },
      { value: "buffalo", label: "Buffalo" },
      { value: "rochester", label: "Rochester" },
      { value: "albany", label: "Albany" },
    ],
    "north-carolina": [
      { value: "charlotte", label: "Charlotte" },
      { value: "raleigh", label: "Raleigh" },
      { value: "greensboro", label: "Greensboro" },
    ],
    "north-dakota": [
      { value: "fargo", label: "Fargo" },
      { value: "bismarck", label: "Bismarck" },
    ],
    ohio: [
      { value: "columbus", label: "Columbus" },
      { value: "cleveland", label: "Cleveland" },
      { value: "cincinnati", label: "Cincinnati" },
    ],
    oklahoma: [
      { value: "oklahoma-city", label: "Oklahoma City" },
      { value: "tulsa", label: "Tulsa" },
    ],
    oregon: [
      { value: "portland", label: "Portland" },
      { value: "eugene", label: "Eugene" },
    ],
    pennsylvania: [
      { value: "philadelphia", label: "Philadelphia" },
      { value: "pittsburgh", label: "Pittsburgh" },
      { value: "allentown", label: "Allentown" },
    ],
    "rhode-island": [
      { value: "providence", label: "Providence" },
      { value: "warwick", label: "Warwick" },
    ],
    "south-carolina": [
      { value: "charleston", label: "Charleston" },
      { value: "columbia", label: "Columbia" },
    ],
    "south-dakota": [
      { value: "sioux-falls", label: "Sioux Falls" },
      { value: "rapid-city", label: "Rapid City" },
    ],
    tennessee: [
      { value: "nashville", label: "Nashville" },
      { value: "memphis", label: "Memphis" },
      { value: "knoxville", label: "Knoxville" },
    ],
    texas: [
      { value: "houston", label: "Houston" },
      { value: "san-antonio", label: "San Antonio" },
      { value: "dallas", label: "Dallas" },
      { value: "austin", label: "Austin" },
      { value: "fort-worth", label: "Fort Worth" },
      { value: "el-paso", label: "El Paso" },
    ],
    utah: [
      { value: "salt-lake-city", label: "Salt Lake City" },
      { value: "west-valley-city", label: "West Valley City" },
    ],
    vermont: [
      { value: "burlington", label: "Burlington" },
      { value: "essex", label: "Essex" },
    ],
    virginia: [
      { value: "virginia-beach", label: "Virginia Beach" },
      { value: "norfolk", label: "Norfolk" },
      { value: "richmond", label: "Richmond" },
    ],
    washington: [
      { value: "seattle", label: "Seattle" },
      { value: "spokane", label: "Spokane" },
      { value: "tacoma", label: "Tacoma" },
    ],
    "west-virginia": [
      { value: "charleston", label: "Charleston" },
      { value: "huntington", label: "Huntington" },
    ],
    wisconsin: [
      { value: "milwaukee", label: "Milwaukee" },
      { value: "madison", label: "Madison" },
    ],
    wyoming: [
      { value: "cheyenne", label: "Cheyenne" },
      { value: "casper", label: "Casper" },
    ],
    "district-columbia": [{ value: "washington", label: "Washington D.C." }],
  },
};

export function findCitiesByRegion(
  countryValue: string,
  regionValue: string
): CityOption[] {
  return CITIES_BY_REGION[countryValue]?.[regionValue] ?? [];
}

