export type RegionOption = {
  value: string;
  label: string;
};

export type CountryOption = {
  value: string;
  label: string;
  regions: RegionOption[];
};

export const COUNTRY_REGION_OPTIONS: CountryOption[] = [
  {
    value: "es",
    label: "España",
    regions: [
      { value: "andalucia", label: "Andalucía" },
      { value: "aragon", label: "Aragón" },
      { value: "asturias", label: "Principado de Asturias" },
      { value: "baleares", label: "Islas Baleares" },
      { value: "canarias", label: "Islas Canarias" },
      { value: "cantabria", label: "Cantabria" },
      { value: "castilla-la-mancha", label: "Castilla-La Mancha" },
      { value: "castilla-y-leon", label: "Castilla y León" },
      { value: "catalunya", label: "Cataluña" },
      { value: "ceuta", label: "Ceuta" },
      { value: "extremadura", label: "Extremadura" },
      { value: "galicia", label: "Galicia" },
      { value: "la-rioja", label: "La Rioja" },
      { value: "madrid", label: "Comunidad de Madrid" },
      { value: "melilla", label: "Melilla" },
      { value: "murcia", label: "Región de Murcia" },
      { value: "navarra", label: "Comunidad Foral de Navarra" },
      { value: "pais-vasco", label: "País Vasco" },
      { value: "valencia", label: "Comunidad Valenciana" },
    ],
  },
  {
    value: "mx",
    label: "México",
    regions: [
      { value: "ags", label: "Aguascalientes" },
      { value: "bc", label: "Baja California" },
      { value: "bcs", label: "Baja California Sur" },
      { value: "cam", label: "Campeche" },
      { value: "chp", label: "Chiapas" },
      { value: "chh", label: "Chihuahua" },
      { value: "cmx", label: "Ciudad de México" },
      { value: "coah", label: "Coahuila" },
      { value: "col", label: "Colima" },
      { value: "dgo", label: "Durango" },
      { value: "gto", label: "Guanajuato" },
      { value: "gro", label: "Guerrero" },
      { value: "hgo", label: "Hidalgo" },
      { value: "jal", label: "Jalisco" },
      { value: "mex", label: "Estado de México" },
      { value: "mich", label: "Michoacán" },
      { value: "mor", label: "Morelos" },
      { value: "nay", label: "Nayarit" },
      { value: "nl", label: "Nuevo León" },
      { value: "oax", label: "Oaxaca" },
      { value: "pue", label: "Puebla" },
      { value: "qro", label: "Querétaro" },
      { value: "qroo", label: "Quintana Roo" },
      { value: "slp", label: "San Luis Potosí" },
      { value: "sin", label: "Sinaloa" },
      { value: "son", label: "Sonora" },
      { value: "tab", label: "Tabasco" },
      { value: "tam", label: "Tamaulipas" },
      { value: "tlx", label: "Tlaxcala" },
      { value: "ver", label: "Veracruz" },
      { value: "yuc", label: "Yucatán" },
      { value: "zac", label: "Zacatecas" },
    ],
  },
  {
    value: "ar",
    label: "Argentina",
    regions: [
      { value: "ba", label: "Buenos Aires" },
      { value: "cat", label: "Catamarca" },
      { value: "cha", label: "Chaco" },
      { value: "chu", label: "Chubut" },
      { value: "cor", label: "Córdoba" },
      { value: "ctes", label: "Corrientes" },
      { value: "er", label: "Entre Ríos" },
      { value: "fo", label: "Formosa" },
      { value: "juj", label: "Jujuy" },
      { value: "lp", label: "La Pampa" },
      { value: "lr", label: "La Rioja" },
      { value: "men", label: "Mendoza" },
      { value: "mis", label: "Misiones" },
      { value: "neu", label: "Neuquén" },
      { value: "rn", label: "Río Negro" },
      { value: "sal", label: "Salta" },
      { value: "sju", label: "San Juan" },
      { value: "sl", label: "San Luis" },
      { value: "sc", label: "Santa Cruz" },
      { value: "sf", label: "Santa Fe" },
      { value: "sgo", label: "Santiago del Estero" },
      { value: "tf", label: "Tierra del Fuego" },
      { value: "tuc", label: "Tucumán" },
    ],
  },
  {
    value: "co",
    label: "Colombia",
    regions: [
      { value: "amazonas", label: "Amazonas" },
      { value: "antioquia", label: "Antioquia" },
      { value: "arauca", label: "Arauca" },
      { value: "atlantico", label: "Atlántico" },
      { value: "bolivar", label: "Bolívar" },
      { value: "boyaca", label: "Boyacá" },
      { value: "caldas", label: "Caldas" },
      { value: "caqueta", label: "Caquetá" },
      { value: "casanare", label: "Casanare" },
      { value: "cauca", label: "Cauca" },
      { value: "cesar", label: "Cesar" },
      { value: "choco", label: "Chocó" },
      { value: "cordoba", label: "Córdoba" },
      { value: "cundinamarca", label: "Cundinamarca" },
      { value: "gua", label: "Guainía" },
      { value: "guajira", label: "La Guajira" },
      { value: "guaviare", label: "Guaviare" },
      { value: "huila", label: "Huila" },
      { value: "magdalena", label: "Magdalena" },
      { value: "meta", label: "Meta" },
      { value: "narino", label: "Nariño" },
      { value: "norte-santander", label: "Norte de Santander" },
      { value: "putumayo", label: "Putumayo" },
      { value: "quindio", label: "Quindío" },
      { value: "risaralda", label: "Risaralda" },
      { value: "san-andres", label: "San Andrés y Providencia" },
      { value: "santander", label: "Santander" },
      { value: "sucre", label: "Sucre" },
      { value: "tolima", label: "Tolima" },
      { value: "valle-cauca", label: "Valle del Cauca" },
      { value: "vaupes", label: "Vaupés" },
      { value: "vichada", label: "Vichada" },
    ],
  },
  {
    value: "cl",
    label: "Chile",
    regions: [
      { value: "arica-parinacota", label: "Arica y Parinacota" },
      { value: "tarapaca", label: "Tarapacá" },
      { value: "antofagasta", label: "Antofagasta" },
      { value: "atacama", label: "Atacama" },
      { value: "coquimbo", label: "Coquimbo" },
      { value: "valparaiso", label: "Valparaíso" },
      { value: "metropolitana", label: "Región Metropolitana de Santiago" },
      { value: "ohiggins", label: "O'Higgins" },
      { value: "maule", label: "Maule" },
      { value: "nuble", label: "Ñuble" },
      { value: "biobio", label: "Biobío" },
      { value: "araucania", label: "La Araucanía" },
      { value: "los-rios", label: "Los Ríos" },
      { value: "los-lagos", label: "Los Lagos" },
      { value: "aysen", label: "Aysén" },
      { value: "magallanes", label: "Magallanes y la Antártica Chilena" },
    ],
  },
];

export function findRegionsByCountry(countryValue: string): RegionOption[] {
  return COUNTRY_REGION_OPTIONS.find((option) => option.value === countryValue)?.regions ?? [];
}


