export type RegionOption = {
  value: string;
  label: string;
};

export type CountryOption = {
  value: string;
  label: string;
  regions: RegionOption[];
};

/**
 * Obtiene el label apropiado para la región según el país
 * España usa "Provincia", otros países usan "Estado"
 */
export function getRegionLabel(countryCode: string | null | undefined): string {
  if (!countryCode) return "Región";
  return countryCode.toLowerCase() === "es" ? "Provincia" : "Estado";
}

/**
 * Obtiene el placeholder apropiado para la región según el país
 */
export function getRegionPlaceholder(countryCode: string | null | undefined, hasCountry: boolean): string {
  if (!hasCountry) return "Selecciona un país primero";
  const label = getRegionLabel(countryCode);
  return `Selecciona una ${label.toLowerCase()}`;
}

/**
 * Obtiene el placeholder para ciudad según si hay región seleccionada
 */
export function getCityPlaceholder(regionLabel: string, hasRegion: boolean): string {
  if (!hasRegion) return `Selecciona una ${regionLabel.toLowerCase()} primero`;
  return "Selecciona una ciudad";
}

export const COUNTRY_REGION_OPTIONS: CountryOption[] = [
  {
    value: "es",
    label: "España",
    regions: [
      { value: "andalucia", label: "Andalucía" },
      { value: "aragon", label: "Aragón" },
      { value: "asturias", label: "Principado de Asturias" },
      { value: "baleares", label: "Islas Baleares" },
      { value: "canarias", label: "Islas Canarias" },
      { value: "cantabria", label: "Cantabria" },
      { value: "castilla-la-mancha", label: "Castilla-La Mancha" },
      { value: "castilla-y-leon", label: "Castilla y León" },
      { value: "catalunya", label: "Cataluña" },
      { value: "ceuta", label: "Ceuta" },
      { value: "extremadura", label: "Extremadura" },
      { value: "galicia", label: "Galicia" },
      { value: "la-rioja", label: "La Rioja" },
      { value: "madrid", label: "Comunidad de Madrid" },
      { value: "melilla", label: "Melilla" },
      { value: "murcia", label: "Región de Murcia" },
      { value: "navarra", label: "Comunidad Foral de Navarra" },
      { value: "pais-vasco", label: "País Vasco" },
      { value: "valencia", label: "Comunidad Valenciana" },
    ],
  },
  {
    value: "mx",
    label: "México",
    regions: [
      { value: "ags", label: "Aguascalientes" },
      { value: "bc", label: "Baja California" },
      { value: "bcs", label: "Baja California Sur" },
      { value: "cam", label: "Campeche" },
      { value: "chp", label: "Chiapas" },
      { value: "chh", label: "Chihuahua" },
      { value: "cmx", label: "Ciudad de México" },
      { value: "coah", label: "Coahuila" },
      { value: "col", label: "Colima" },
      { value: "dgo", label: "Durango" },
      { value: "gto", label: "Guanajuato" },
      { value: "gro", label: "Guerrero" },
      { value: "hgo", label: "Hidalgo" },
      { value: "jal", label: "Jalisco" },
      { value: "mex", label: "Estado de México" },
      { value: "mich", label: "Michoacán" },
      { value: "mor", label: "Morelos" },
      { value: "nay", label: "Nayarit" },
      { value: "nl", label: "Nuevo León" },
      { value: "oax", label: "Oaxaca" },
      { value: "pue", label: "Puebla" },
      { value: "qro", label: "Querétaro" },
      { value: "qroo", label: "Quintana Roo" },
      { value: "slp", label: "San Luis Potosí" },
      { value: "sin", label: "Sinaloa" },
      { value: "son", label: "Sonora" },
      { value: "tab", label: "Tabasco" },
      { value: "tam", label: "Tamaulipas" },
      { value: "tlx", label: "Tlaxcala" },
      { value: "ver", label: "Veracruz" },
      { value: "yuc", label: "Yucatán" },
      { value: "zac", label: "Zacatecas" },
    ],
  },
  {
    value: "ar",
    label: "Argentina",
    regions: [
      { value: "ba", label: "Buenos Aires" },
      { value: "cat", label: "Catamarca" },
      { value: "cha", label: "Chaco" },
      { value: "chu", label: "Chubut" },
      { value: "cor", label: "Córdoba" },
      { value: "ctes", label: "Corrientes" },
      { value: "er", label: "Entre Ríos" },
      { value: "fo", label: "Formosa" },
      { value: "juj", label: "Jujuy" },
      { value: "lp", label: "La Pampa" },
      { value: "lr", label: "La Rioja" },
      { value: "men", label: "Mendoza" },
      { value: "mis", label: "Misiones" },
      { value: "neu", label: "Neuquén" },
      { value: "rn", label: "Río Negro" },
      { value: "sal", label: "Salta" },
      { value: "sju", label: "San Juan" },
      { value: "sl", label: "San Luis" },
      { value: "sc", label: "Santa Cruz" },
      { value: "sf", label: "Santa Fe" },
      { value: "sgo", label: "Santiago del Estero" },
      { value: "tf", label: "Tierra del Fuego" },
      { value: "tuc", label: "Tucumán" },
    ],
  },
  {
    value: "co",
    label: "Colombia",
    regions: [
      { value: "amazonas", label: "Amazonas" },
      { value: "antioquia", label: "Antioquia" },
      { value: "arauca", label: "Arauca" },
      { value: "atlantico", label: "Atlántico" },
      { value: "bolivar", label: "Bolívar" },
      { value: "boyaca", label: "Boyacá" },
      { value: "caldas", label: "Caldas" },
      { value: "caqueta", label: "Caquetá" },
      { value: "casanare", label: "Casanare" },
      { value: "cauca", label: "Cauca" },
      { value: "cesar", label: "Cesar" },
      { value: "choco", label: "Chocó" },
      { value: "cordoba", label: "Córdoba" },
      { value: "cundinamarca", label: "Cundinamarca" },
      { value: "gua", label: "Guainía" },
      { value: "guajira", label: "La Guajira" },
      { value: "guaviare", label: "Guaviare" },
      { value: "huila", label: "Huila" },
      { value: "magdalena", label: "Magdalena" },
      { value: "meta", label: "Meta" },
      { value: "narino", label: "Nariño" },
      { value: "norte-santander", label: "Norte de Santander" },
      { value: "putumayo", label: "Putumayo" },
      { value: "quindio", label: "Quindío" },
      { value: "risaralda", label: "Risaralda" },
      { value: "san-andres", label: "San Andrés y Providencia" },
      { value: "santander", label: "Santander" },
      { value: "sucre", label: "Sucre" },
      { value: "tolima", label: "Tolima" },
      { value: "valle-cauca", label: "Valle del Cauca" },
      { value: "vaupes", label: "Vaupés" },
      { value: "vichada", label: "Vichada" },
    ],
  },
  {
    value: "cl",
    label: "Chile",
    regions: [
      { value: "arica-parinacota", label: "Arica y Parinacota" },
      { value: "tarapaca", label: "Tarapacá" },
      { value: "antofagasta", label: "Antofagasta" },
      { value: "atacama", label: "Atacama" },
      { value: "coquimbo", label: "Coquimbo" },
      { value: "valparaiso", label: "Valparaíso" },
      { value: "metropolitana", label: "Región Metropolitana de Santiago" },
      { value: "ohiggins", label: "O'Higgins" },
      { value: "maule", label: "Maule" },
      { value: "nuble", label: "Ñuble" },
      { value: "biobio", label: "Biobío" },
      { value: "araucania", label: "La Araucanía" },
      { value: "los-rios", label: "Los Ríos" },
      { value: "los-lagos", label: "Los Lagos" },
      { value: "aysen", label: "Aysén" },
      { value: "magallanes", label: "Magallanes y la Antártica Chilena" },
    ],
  },
  {
    value: "pe",
    label: "Perú",
    regions: [
      { value: "amazonas", label: "Amazonas" },
      { value: "ancash", label: "Áncash" },
      { value: "apurimac", label: "Apurímac" },
      { value: "arequipa", label: "Arequipa" },
      { value: "ayacucho", label: "Ayacucho" },
      { value: "cajamarca", label: "Cajamarca" },
      { value: "callao", label: "Callao" },
      { value: "cusco", label: "Cusco" },
      { value: "huancavelica", label: "Huancavelica" },
      { value: "huanuco", label: "Huánuco" },
      { value: "ica", label: "Ica" },
      { value: "junin", label: "Junín" },
      { value: "la-libertad", label: "La Libertad" },
      { value: "lambayeque", label: "Lambayeque" },
      { value: "lima", label: "Lima" },
      { value: "loreto", label: "Loreto" },
      { value: "madre-de-dios", label: "Madre de Dios" },
      { value: "moquegua", label: "Moquegua" },
      { value: "pasco", label: "Pasco" },
      { value: "piura", label: "Piura" },
      { value: "puno", label: "Puno" },
      { value: "san-martin", label: "San Martín" },
      { value: "tacna", label: "Tacna" },
      { value: "tumbes", label: "Tumbes" },
      { value: "ucayali", label: "Ucayali" },
    ],
  },
  {
    value: "ve",
    label: "Venezuela",
    regions: [
      { value: "amazonas", label: "Amazonas" },
      { value: "anzoategui", label: "Anzoátegui" },
      { value: "apure", label: "Apure" },
      { value: "aragua", label: "Aragua" },
      { value: "barinas", label: "Barinas" },
      { value: "bolivar", label: "Bolívar" },
      { value: "carabobo", label: "Carabobo" },
      { value: "cojedes", label: "Cojedes" },
      { value: "delta-amacuro", label: "Delta Amacuro" },
      { value: "distrito-capital", label: "Distrito Capital" },
      { value: "falcon", label: "Falcón" },
      { value: "guarico", label: "Guárico" },
      { value: "lara", label: "Lara" },
      { value: "merida", label: "Mérida" },
      { value: "miranda", label: "Miranda" },
      { value: "monagas", label: "Monagas" },
      { value: "nueva-esparta", label: "Nueva Esparta" },
      { value: "portuguesa", label: "Portuguesa" },
      { value: "sucre", label: "Sucre" },
      { value: "tachira", label: "Táchira" },
      { value: "trujillo", label: "Trujillo" },
      { value: "vargas", label: "Vargas" },
      { value: "yaracuy", label: "Yaracuy" },
      { value: "zulia", label: "Zulia" },
    ],
  },
  {
    value: "ec",
    label: "Ecuador",
    regions: [
      { value: "azuay", label: "Azuay" },
      { value: "bolivar", label: "Bolívar" },
      { value: "canar", label: "Cañar" },
      { value: "carchi", label: "Carchi" },
      { value: "chimborazo", label: "Chimborazo" },
      { value: "cotopaxi", label: "Cotopaxi" },
      { value: "el-oro", label: "El Oro" },
      { value: "esmeraldas", label: "Esmeraldas" },
      { value: "galapagos", label: "Galápagos" },
      { value: "guayas", label: "Guayas" },
      { value: "imbabura", label: "Imbabura" },
      { value: "loja", label: "Loja" },
      { value: "los-rios", label: "Los Ríos" },
      { value: "manabi", label: "Manabí" },
      { value: "morona-santiago", label: "Morona Santiago" },
      { value: "napo", label: "Napo" },
      { value: "orellana", label: "Orellana" },
      { value: "pastaza", label: "Pastaza" },
      { value: "pichincha", label: "Pichincha" },
      { value: "santa-elena", label: "Santa Elena" },
      { value: "santo-domingo", label: "Santo Domingo de los Tsáchilas" },
      { value: "sucumbios", label: "Sucumbíos" },
      { value: "tungurahua", label: "Tungurahua" },
      { value: "zamora-chinchipe", label: "Zamora Chinchipe" },
    ],
  },
  {
    value: "gt",
    label: "Guatemala",
    regions: [
      { value: "alta-verapaz", label: "Alta Verapaz" },
      { value: "baja-verapaz", label: "Baja Verapaz" },
      { value: "chimaltenango", label: "Chimaltenango" },
      { value: "chiquimula", label: "Chiquimula" },
      { value: "el-progreso", label: "El Progreso" },
      { value: "escuintla", label: "Escuintla" },
      { value: "guatemala", label: "Guatemala" },
      { value: "huehuetenango", label: "Huehuetenango" },
      { value: "izabal", label: "Izabal" },
      { value: "jalapa", label: "Jalapa" },
      { value: "jutiapa", label: "Jutiapa" },
      { value: "peten", label: "Petén" },
      { value: "quetzaltenango", label: "Quetzaltenango" },
      { value: "quiche", label: "Quiché" },
      { value: "retalhuleu", label: "Retalhuleu" },
      { value: "sacatepequez", label: "Sacatepéquez" },
      { value: "san-marcos", label: "San Marcos" },
      { value: "santa-rosa", label: "Santa Rosa" },
      { value: "solola", label: "Sololá" },
      { value: "suchitepequez", label: "Suchitepéquez" },
      { value: "totonicapan", label: "Totonicapán" },
      { value: "zacapa", label: "Zacapa" },
    ],
  },
  {
    value: "cu",
    label: "Cuba",
    regions: [
      { value: "artemisa", label: "Artemisa" },
      { value: "camaguey", label: "Camagüey" },
      { value: "ciego-avila", label: "Ciego de Ávila" },
      { value: "cienfuegos", label: "Cienfuegos" },
      { value: "granma", label: "Granma" },
      { value: "guantanamo", label: "Guantánamo" },
      { value: "holguin", label: "Holguín" },
      { value: "isla-juventud", label: "Isla de la Juventud" },
      { value: "la-habana", label: "La Habana" },
      { value: "las-tunas", label: "Las Tunas" },
      { value: "matanzas", label: "Matanzas" },
      { value: "mayabeque", label: "Mayabeque" },
      { value: "pinar-del-rio", label: "Pinar del Río" },
      { value: "sancti-spiritus", label: "Sancti Spíritus" },
      { value: "santiago-cuba", label: "Santiago de Cuba" },
      { value: "villa-clara", label: "Villa Clara" },
    ],
  },
  {
    value: "do",
    label: "República Dominicana",
    regions: [
      { value: "azua", label: "Azua" },
      { value: "baoruco", label: "Baoruco" },
      { value: "barahona", label: "Barahona" },
      { value: "dajabon", label: "Dajabón" },
      { value: "distrito-nacional", label: "Distrito Nacional" },
      { value: "duarte", label: "Duarte" },
      { value: "espailat", label: "Espaillat" },
      { value: "hato-mayor", label: "Hato Mayor" },
      { value: "hermanas-mirabal", label: "Hermanas Mirabal" },
      { value: "independencia", label: "Independencia" },
      { value: "la-altagracia", label: "La Altagracia" },
      { value: "la-romana", label: "La Romana" },
      { value: "la-vega", label: "La Vega" },
      { value: "maria-trinidad-sanchez", label: "María Trinidad Sánchez" },
      { value: "monsenor-nouel", label: "Monseñor Nouel" },
      { value: "monte-cristi", label: "Monte Cristi" },
      { value: "monte-plata", label: "Monte Plata" },
      { value: "pedernales", label: "Pedernales" },
      { value: "peravia", label: "Peravia" },
      { value: "puerto-plata", label: "Puerto Plata" },
      { value: "samana", label: "Samaná" },
      { value: "san-cristobal", label: "San Cristóbal" },
      { value: "san-jose-ooa", label: "San José de Ocoa" },
      { value: "san-juan", label: "San Juan" },
      { value: "san-pedro-macoris", label: "San Pedro de Macorís" },
      { value: "sanchez-ramirez", label: "Sánchez Ramírez" },
      { value: "santiago", label: "Santiago" },
      { value: "santiago-rodriguez", label: "Santiago Rodríguez" },
      { value: "santo-domingo", label: "Santo Domingo" },
      { value: "valverde", label: "Valverde" },
    ],
  },
  {
    value: "hn",
    label: "Honduras",
    regions: [
      { value: "atlantida", label: "Atlántida" },
      { value: "choluteca", label: "Choluteca" },
      { value: "colon", label: "Colón" },
      { value: "comayagua", label: "Comayagua" },
      { value: "copan", label: "Copán" },
      { value: "cortes", label: "Cortés" },
      { value: "el-paraiso", label: "El Paraíso" },
      { value: "francisco-morazan", label: "Francisco Morazán" },
      { value: "gracias-dios", label: "Gracias a Dios" },
      { value: "intibuca", label: "Intibucá" },
      { value: "islas-bahia", label: "Islas de la Bahía" },
      { value: "la-paz", label: "La Paz" },
      { value: "lempira", label: "Lempira" },
      { value: "ocotepeque", label: "Ocotepeque" },
      { value: "olancho", label: "Olancho" },
      { value: "santa-barbara", label: "Santa Bárbara" },
      { value: "valle", label: "Valle" },
      { value: "yoro", label: "Yoro" },
    ],
  },
  {
    value: "sv",
    label: "El Salvador",
    regions: [
      { value: "ahuachapan", label: "Ahuachapán" },
      { value: "cabanas", label: "Cabañas" },
      { value: "chalatenango", label: "Chalatenango" },
      { value: "cuscatlan", label: "Cuscatlán" },
      { value: "la-libertad", label: "La Libertad" },
      { value: "la-paz", label: "La Paz" },
      { value: "la-union", label: "La Unión" },
      { value: "morazan", label: "Morazán" },
      { value: "san-miguel", label: "San Miguel" },
      { value: "san-salvador", label: "San Salvador" },
      { value: "san-vicente", label: "San Vicente" },
      { value: "santa-ana", label: "Santa Ana" },
      { value: "sonsonate", label: "Sonsonate" },
      { value: "usulutan", label: "Usulután" },
    ],
  },
  {
    value: "ni",
    label: "Nicaragua",
    regions: [
      { value: "boaco", label: "Boaco" },
      { value: "carazo", label: "Carazo" },
      { value: "chinandega", label: "Chinandega" },
      { value: "chontales", label: "Chontales" },
      { value: "esteli", label: "Estelí" },
      { value: "granada", label: "Granada" },
      { value: "jinotega", label: "Jinotega" },
      { value: "leon", label: "León" },
      { value: "madriz", label: "Madriz" },
      { value: "managua", label: "Managua" },
      { value: "masaya", label: "Masaya" },
      { value: "matagalpa", label: "Matagalpa" },
      { value: "nueva-segovia", label: "Nueva Segovia" },
      { value: "rio-san-juan", label: "Río San Juan" },
      { value: "rivas", label: "Rivas" },
      { value: "costa-caribe-norte", label: "Costa Caribe Norte" },
      { value: "costa-caribe-sur", label: "Costa Caribe Sur" },
    ],
  },
  {
    value: "cr",
    label: "Costa Rica",
    regions: [
      { value: "alajuela", label: "Alajuela" },
      { value: "cartago", label: "Cartago" },
      { value: "guanacaste", label: "Guanacaste" },
      { value: "heredia", label: "Heredia" },
      { value: "limon", label: "Limón" },
      { value: "puntarenas", label: "Puntarenas" },
      { value: "san-jose", label: "San José" },
    ],
  },
  {
    value: "pa",
    label: "Panamá",
    regions: [
      { value: "bocas-del-toro", label: "Bocas del Toro" },
      { value: "chiriqui", label: "Chiriquí" },
      { value: "cocle", label: "Coclé" },
      { value: "colon", label: "Colón" },
      { value: "darien", label: "Darién" },
      { value: "herrera", label: "Herrera" },
      { value: "los-santos", label: "Los Santos" },
      { value: "panama", label: "Panamá" },
      { value: "panama-oeste", label: "Panamá Oeste" },
      { value: "veraguas", label: "Veraguas" },
      { value: "guna-yala", label: "Guna Yala" },
      { value: "embera-wounaan", label: "Emberá-Wounaan" },
      { value: "ngabe-bugle", label: "Ngäbe-Buglé" },
    ],
  },
  {
    value: "py",
    label: "Paraguay",
    regions: [
      { value: "asuncion", label: "Asunción" },
      { value: "alto-parana", label: "Alto Paraná" },
      { value: "amambay", label: "Amambay" },
      { value: "boqueron", label: "Boquerón" },
      { value: "caaguazu", label: "Caaguazú" },
      { value: "caazapa", label: "Caazapá" },
      { value: "canindeyu", label: "Canindeyú" },
      { value: "central", label: "Central" },
      { value: "concepcion", label: "Concepción" },
      { value: "cordillera", label: "Cordillera" },
      { value: "guaira", label: "Guairá" },
      { value: "itapua", label: "Itapúa" },
      { value: "misiones", label: "Misiones" },
      { value: "neembucu", label: "Ñeembucú" },
      { value: "paraguari", label: "Paraguarí" },
      { value: "presidente-hayes", label: "Presidente Hayes" },
      { value: "san-pedro", label: "San Pedro" },
      { value: "alto-paraguay", label: "Alto Paraguay" },
    ],
  },
  {
    value: "uy",
    label: "Uruguay",
    regions: [
      { value: "artigas", label: "Artigas" },
      { value: "canelones", label: "Canelones" },
      { value: "cerro-largo", label: "Cerro Largo" },
      { value: "colonia", label: "Colonia" },
      { value: "durazno", label: "Durazno" },
      { value: "flores", label: "Flores" },
      { value: "florida", label: "Florida" },
      { value: "lavalleja", label: "Lavalleja" },
      { value: "maldonado", label: "Maldonado" },
      { value: "montevideo", label: "Montevideo" },
      { value: "paysandu", label: "Paysandú" },
      { value: "rio-negro", label: "Río Negro" },
      { value: "rivera", label: "Rivera" },
      { value: "rocha", label: "Rocha" },
      { value: "salto", label: "Salto" },
      { value: "san-jose", label: "San José" },
      { value: "soriano", label: "Soriano" },
      { value: "tacuarembo", label: "Tacuarembó" },
      { value: "treinta-tres", label: "Treinta y Tres" },
    ],
  },
  {
    value: "bo",
    label: "Bolivia",
    regions: [
      { value: "chuquisaca", label: "Chuquisaca" },
      { value: "cochabamba", label: "Cochabamba" },
      { value: "beni", label: "Beni" },
      { value: "la-paz", label: "La Paz" },
      { value: "oruro", label: "Oruro" },
      { value: "pando", label: "Pando" },
      { value: "potosi", label: "Potosí" },
      { value: "santa-cruz", label: "Santa Cruz" },
      { value: "tarija", label: "Tarija" },
    ],
  },
  {
    value: "pr",
    label: "Puerto Rico",
    regions: [
      { value: "aguadilla", label: "Aguadilla" },
      { value: "arecibo", label: "Arecibo" },
      { value: "bayamon", label: "Bayamón" },
      { value: "carolina", label: "Carolina" },
      { value: "caguas", label: "Caguas" },
      { value: "mayaguez", label: "Mayagüez" },
      { value: "ponce", label: "Ponce" },
      { value: "san-juan", label: "San Juan" },
    ],
  },
  {
    value: "us",
    label: "Estados Unidos",
    regions: [
      { value: "alabama", label: "Alabama" },
      { value: "alaska", label: "Alaska" },
      { value: "arizona", label: "Arizona" },
      { value: "arkansas", label: "Arkansas" },
      { value: "california", label: "California" },
      { value: "colorado", label: "Colorado" },
      { value: "connecticut", label: "Connecticut" },
      { value: "delaware", label: "Delaware" },
      { value: "florida", label: "Florida" },
      { value: "georgia", label: "Georgia" },
      { value: "hawaii", label: "Hawaii" },
      { value: "idaho", label: "Idaho" },
      { value: "illinois", label: "Illinois" },
      { value: "indiana", label: "Indiana" },
      { value: "iowa", label: "Iowa" },
      { value: "kansas", label: "Kansas" },
      { value: "kentucky", label: "Kentucky" },
      { value: "louisiana", label: "Louisiana" },
      { value: "maine", label: "Maine" },
      { value: "maryland", label: "Maryland" },
      { value: "massachusetts", label: "Massachusetts" },
      { value: "michigan", label: "Michigan" },
      { value: "minnesota", label: "Minnesota" },
      { value: "mississippi", label: "Mississippi" },
      { value: "missouri", label: "Missouri" },
      { value: "montana", label: "Montana" },
      { value: "nebraska", label: "Nebraska" },
      { value: "nevada", label: "Nevada" },
      { value: "new-hampshire", label: "New Hampshire" },
      { value: "new-jersey", label: "New Jersey" },
      { value: "new-mexico", label: "New Mexico" },
      { value: "new-york", label: "New York" },
      { value: "north-carolina", label: "North Carolina" },
      { value: "north-dakota", label: "North Dakota" },
      { value: "ohio", label: "Ohio" },
      { value: "oklahoma", label: "Oklahoma" },
      { value: "oregon", label: "Oregon" },
      { value: "pennsylvania", label: "Pennsylvania" },
      { value: "rhode-island", label: "Rhode Island" },
      { value: "south-carolina", label: "South Carolina" },
      { value: "south-dakota", label: "South Dakota" },
      { value: "tennessee", label: "Tennessee" },
      { value: "texas", label: "Texas" },
      { value: "utah", label: "Utah" },
      { value: "vermont", label: "Vermont" },
      { value: "virginia", label: "Virginia" },
      { value: "washington", label: "Washington" },
      { value: "west-virginia", label: "West Virginia" },
      { value: "wisconsin", label: "Wisconsin" },
      { value: "wyoming", label: "Wyoming" },
      { value: "district-columbia", label: "District of Columbia" },
    ],
  },
];

export function findRegionsByCountry(countryValue: string): RegionOption[] {
  return COUNTRY_REGION_OPTIONS.find((option) => option.value === countryValue)?.regions ?? [];
}


