import { boolean, index, integer, pgTable, text, time, timestamp, uuid } from "drizzle-orm/pg-core";

import { academies } from "./academies";
import { groups } from "./groups";

export const classes = pgTable(
  "classes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id").notNull(),
    academyId: uuid("academy_id")
      .notNull()
      .references(() => academies.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    weekday: integer("weekday"),
    startTime: time("start_time"),
    endTime: time("end_time"),
    capacity: integer("capacity").default(1),
    isExtra: boolean("is_extra").default(false).notNull(),
    groupId: uuid("group_id").references(() => groups.id, { onDelete: "set null" }),
    autoGenerateSessions: boolean("auto_generate_sessions").notNull().default(false),
    autoGenerateFrequency: text("auto_generate_frequency").default("monthly"),
    lastAutoGeneratedAt: timestamp("last_auto_generated_at", { withTimezone: true }),
    autoGenerateDaysAhead: integer("auto_generate_days_ahead").default(30),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    tenantAcademyIdx: index("classes_tenant_academy_idx").on(table.tenantId, table.academyId),
    groupIdIdx: index("classes_group_id_idx").on(table.groupId),
    startTimeEndTimeIdx: index("classes_start_time_end_time_idx").on(table.startTime, table.endTime),
  })
);

