import { NextResponse } from "next/server";
import { z } from "zod";
import { eq, and } from "drizzle-orm";

import { db } from "@/db";
import { classes } from "@/db/schema";
import { withTenant } from "@/lib/authz";

const bodySchema = z.object({
  autoGenerateSessions: z.boolean(),
  autoGenerateFrequency: z.enum(["monthly", "quarterly"]).optional(),
  autoGenerateDaysAhead: z.number().min(7).max(90).optional(),
});

export const PUT = withTenant(async (request, context) => {
  if (!context.tenantId) {
    return NextResponse.json({ error: "TENANT_REQUIRED" }, { status: 400 });
  }

  const classId = (context.params as { classId?: string } | undefined)?.classId;

  if (!classId) {
    return NextResponse.json({ error: "CLASS_ID_REQUIRED" }, { status: 400 });
  }

  const body = bodySchema.parse(await request.json());

  // Validar que la clase existe y pertenece al tenant
  const [classRow] = await db
    .select({
      id: classes.id,
      lastAutoGeneratedAt: classes.lastAutoGeneratedAt,
    })
    .from(classes)
    .where(and(eq(classes.id, classId), eq(classes.tenantId, context.tenantId)))
    .limit(1);

  if (!classRow) {
    return NextResponse.json({ error: "CLASS_NOT_FOUND" }, { status: 404 });
  }

  // Preparar actualización
  const updateData: {
    autoGenerateSessions: boolean;
    autoGenerateFrequency: string | null;
    autoGenerateDaysAhead: number | null;
    lastAutoGeneratedAt?: Date;
  } = {
    autoGenerateSessions: body.autoGenerateSessions,
    autoGenerateFrequency: body.autoGenerateFrequency || null,
    autoGenerateDaysAhead: body.autoGenerateDaysAhead || null,
  };

  // Si se activa por primera vez, establecer fecha de última generación
  if (body.autoGenerateSessions && !classRow.lastAutoGeneratedAt) {
    updateData.lastAutoGeneratedAt = new Date();
  }

  // Actualizar configuración
  await db
    .update(classes)
    .set(updateData)
    .where(eq(classes.id, classId));

  return NextResponse.json({ ok: true });
});

export const GET = withTenant(async (_request, context) => {
  if (!context.tenantId) {
    return NextResponse.json({ error: "TENANT_REQUIRED" }, { status: 400 });
  }

  const classId = (context.params as { classId?: string } | undefined)?.classId;

  if (!classId) {
    return NextResponse.json({ error: "CLASS_ID_REQUIRED" }, { status: 400 });
  }

  // Obtener configuración de la clase
  const [classRow] = await db
    .select({
      autoGenerateSessions: classes.autoGenerateSessions,
      autoGenerateFrequency: classes.autoGenerateFrequency,
      lastAutoGeneratedAt: classes.lastAutoGeneratedAt,
      autoGenerateDaysAhead: classes.autoGenerateDaysAhead,
    })
    .from(classes)
    .where(and(eq(classes.id, classId), eq(classes.tenantId, context.tenantId)))
    .limit(1);

  if (!classRow) {
    return NextResponse.json({ error: "CLASS_NOT_FOUND" }, { status: 404 });
  }

  return NextResponse.json({
    autoGenerateSessions: classRow.autoGenerateSessions ?? false,
    autoGenerateFrequency: classRow.autoGenerateFrequency,
    lastAutoGeneratedAt: classRow.lastAutoGeneratedAt?.toISOString() || null,
    autoGenerateDaysAhead: classRow.autoGenerateDaysAhead ?? 30,
  });
});

