"use client";

import { useState, useEffect } from "react";
import { Calendar, Settings, AlertCircle, CheckCircle2, Clock, Loader2 } from "lucide-react";
import { format, addDays, differenceInDays } from "date-fns";
import { es } from "date-fns/locale";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { GenerateSessionsDialog } from "./GenerateSessionsDialog";

interface RecurringSessionsManagerProps {
  classId: string;
  className: string;
  weekdays: number[];
  startTime: string | null;
  endTime: string | null;
  autoGenerateSessions: boolean;
  autoGenerateFrequency: string | null;
  lastAutoGeneratedAt: string | null;
  autoGenerateDaysAhead: number | null;
  onSettingsUpdated?: () => void;
}

const WEEKDAY_LABELS: Record<number, string> = {
  0: "Domingo",
  1: "Lunes",
  2: "Martes",
  3: "Miércoles",
  4: "Jueves",
  5: "Viernes",
  6: "Sábado",
};

export function RecurringSessionsManager({
  classId,
  className,
  weekdays,
  startTime,
  endTime,
  autoGenerateSessions: initialAutoGenerate,
  autoGenerateFrequency: initialFrequency,
  lastAutoGeneratedAt,
  autoGenerateDaysAhead: initialDaysAhead,
  onSettingsUpdated,
}: RecurringSessionsManagerProps) {
  const [autoGenerate, setAutoGenerate] = useState(initialAutoGenerate);
  const [frequency, setFrequency] = useState(initialFrequency || "monthly");
  const [daysAhead, setDaysAhead] = useState(initialDaysAhead || 30);
  const [isSaving, setIsSaving] = useState(false);
  const [isGeneratingDialogOpen, setIsGeneratingDialogOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const handleSaveSettings = async () => {
    setIsSaving(true);
    setError(null);
    setSuccess(null);

    try {
      const response = await fetch(`/api/classes/${classId}/recurring-settings`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          autoGenerateSessions: autoGenerate,
          autoGenerateFrequency: frequency,
          autoGenerateDaysAhead: daysAhead,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || data.error || "Error al guardar configuración");
      }

      setSuccess("Configuración guardada correctamente");
      onSettingsUpdated?.();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err: any) {
      setError(err.message || "Error al guardar configuración");
    } finally {
      setIsSaving(false);
    }
  };

  const getNextGenerationDate = () => {
    if (!lastAutoGeneratedAt) return null;
    const lastDate = new Date(lastAutoGeneratedAt);
    const nextDate = new Date(lastDate);
    
    if (frequency === "monthly") {
      nextDate.setMonth(nextDate.getMonth() + 1);
    } else if (frequency === "quarterly") {
      nextDate.setMonth(nextDate.getMonth() + 3);
    }
    
    return nextDate;
  };

  const getSessionsNeeded = () => {
    if (!autoGenerate || !lastAutoGeneratedAt) return null;
    
    const lastDate = new Date(lastAutoGeneratedAt);
    const targetDate = addDays(new Date(), daysAhead);
    
    if (targetDate <= lastDate) return 0;
    
    // Calcular cuántas sesiones faltan por generar
    const daysDiff = differenceInDays(targetDate, lastDate);
    let sessionsNeeded = 0;
    
    for (const weekday of weekdays) {
      // Aproximación simple: dividir días por 7 y contar weekdays
      sessionsNeeded += Math.floor(daysDiff / 7);
    }
    
    return sessionsNeeded;
  };

  const nextGeneration = getNextGenerationDate();
  const sessionsNeeded = getSessionsNeeded();

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Settings className="h-5 w-5" />
                Generación Automática de Sesiones
              </CardTitle>
              <CardDescription>
                Configura la generación automática de sesiones recurrentes para esta clase
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="auto-generate">Activar generación automática</Label>
              <p className="text-sm text-muted-foreground">
                Las sesiones se generarán automáticamente según la frecuencia configurada
              </p>
            </div>
            <Switch
              id="auto-generate"
              checked={autoGenerate}
              onCheckedChange={setAutoGenerate}
            />
          </div>

          {autoGenerate && (
            <>
              <div className="space-y-2">
                <Label htmlFor="frequency">Frecuencia de generación</Label>
                <select
                  id="frequency"
                  value={frequency}
                  onChange={(e) => setFrequency(e.target.value)}
                  className="flex h-10 w-full rounded-md border border-border bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  <option value="monthly">Mensual</option>
                  <option value="quarterly">Trimestral</option>
                </select>
                <p className="text-sm text-muted-foreground">
                  Con qué frecuencia se generarán las sesiones automáticamente
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="days-ahead">Días de anticipación</Label>
                <Input
                  id="days-ahead"
                  type="number"
                  min="7"
                  max="90"
                  value={daysAhead}
                  onChange={(e) => setDaysAhead(Number(e.target.value))}
                />
                <p className="text-sm text-muted-foreground">
                  Cuántos días de anticipación mantener sesiones generadas (7-90 días)
                </p>
              </div>
            </>
          )}

          {error && (
            <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-900">
              {error}
            </div>
          )}

          {success && (
            <div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-900">
              {success}
            </div>
          )}

          <div className="flex gap-2">
            <Button onClick={handleSaveSettings} disabled={isSaving}>
              {isSaving ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Guardando...
                </>
              ) : (
                "Guardar configuración"
              )}
            </Button>
            <Button
              variant="outline"
              onClick={() => setIsGeneratingDialogOpen(true)}
            >
              <Calendar className="mr-2 h-4 w-4" />
              Generar sesiones manualmente
            </Button>
          </div>
        </CardContent>
      </Card>

      {autoGenerate && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="h-5 w-5" />
              Estado de Generación
            </CardTitle>
            <CardDescription>
              Información sobre la última generación y próximas sesiones
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {lastAutoGeneratedAt ? (
              <>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">Última generación:</span>
                  <Badge variant="outline">
                    {format(new Date(lastAutoGeneratedAt), "PPP", { locale: es })}
                  </Badge>
                </div>
                {nextGeneration && (
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">Próxima generación:</span>
                    <Badge variant="outline">
                      {format(nextGeneration, "PPP", { locale: es })}
                    </Badge>
                  </div>
                )}
                {sessionsNeeded !== null && sessionsNeeded > 0 && (
                  <div className="rounded-lg border border-amber-200 bg-amber-50 p-3">
                    <div className="flex items-center gap-2">
                      <AlertCircle className="h-4 w-4 text-amber-600" />
                      <p className="text-sm text-amber-900">
                        Faltan aproximadamente <strong>{sessionsNeeded} sesiones</strong> por generar.
                        Considera generar sesiones manualmente.
                      </p>
                    </div>
                  </div>
                )}
                {sessionsNeeded === 0 && (
                  <div className="rounded-lg border border-green-200 bg-green-50 p-3">
                    <div className="flex items-center gap-2">
                      <CheckCircle2 className="h-4 w-4 text-green-600" />
                      <p className="text-sm text-green-900">
                        Todas las sesiones necesarias están generadas.
                      </p>
                    </div>
                  </div>
                )}
              </>
            ) : (
              <div className="rounded-lg border border-blue-200 bg-blue-50 p-3">
                <p className="text-sm text-blue-900">
                  Aún no se han generado sesiones automáticamente. La primera generación se realizará
                  cuando se active la generación automática.
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      <GenerateSessionsDialog
        classId={classId}
        className={className}
        weekdays={weekdays}
        startTime={startTime}
        endTime={endTime}
        open={isGeneratingDialogOpen}
        onClose={() => setIsGeneratingDialogOpen(false)}
        onGenerated={() => {
          onSettingsUpdated?.();
          setIsGeneratingDialogOpen(false);
        }}
      />
    </div>
  );
}

